import test from "node:test";
import assert from "node:assert/strict";
import {Keypair,Transaction,Connection} from "@solana/web3.js";
import {createBurnCheckedInstruction,createTransferCheckedInstruction,TOKEN_PROGRAM_ID} from "../server/token";
import bs58 from "bs58";
import {hash} from "../server/auth";
import {verify,GENESIS,USDC} from "../server/chain";
import {PublicKey} from "@solana/web3.js";
import type {Quote} from "../server/finance";
function fixture(kind:"burn"|"purchase"="burn"){const wallet=Keypair.generate(),mint=kind==="purchase"?new PublicKey(USDC):Keypair.generate().publicKey,source=Keypair.generate().publicKey,destination=Keypair.generate().publicKey;const tx=new Transaction({feePayer:wallet.publicKey,recentBlockhash:Keypair.generate().publicKey.toBase58()});tx.add(kind==="burn"?createBurnCheckedInstruction(source,mint,wallet.publicKey,1000000n,6):createTransferCheckedInstruction(source,mint,destination,wallet.publicKey,1000000n,6));tx.sign(wallet);const signature=bs58.encode(tx.signature!);const q:Quote={id:"quote",wallet:wallet.publicKey.toBase58(),kind,atomic_amount:"1000000",credits:1000000000,expires:Date.now()+60000,state:"issued",message_hash:hash(tx.serializeMessage()),transaction_base64:tx.serialize().toString("base64"),reference:Keypair.generate().publicKey.toBase58(),last_valid_height:1,blockhash:tx.recentBlockhash!,fee:5000,signature:null,mint:mint.toBase58(),decimals:6,recipient:kind==="purchase"?destination.toBase58():null,created:Date.now()};const parsed:any={meta:{err:null},transaction:{message:{accountKeys:[{signer:true,pubkey:wallet.publicKey}],instructions:[{programId:TOKEN_PROGRAM_ID,parsed:{type:kind==="burn"?"burnChecked":"transferChecked",info:{mint:mint.toBase58(),authority:wallet.publicKey.toBase58(),destination:destination.toBase58(),tokenAmount:{amount:"1000000",decimals:6}}}}]}}};const raw:any={meta:{err:null,fee:5000},slot:123,transaction:{message:tx.compileMessage()}};const client={getGenesisHash:async()=>GENESIS,getSignatureStatuses:async()=>({value:[{confirmationStatus:"finalized",err:null}]}),getTransaction:async()=>raw,getParsedTransaction:async()=>parsed} as unknown as Connection;return {q,signature,client,parsed,raw};}
 test("actual canonical burn instruction and finalized message are verified in controlled chain fixture",async()=>{const {q,signature,client}=fixture();assert.deepEqual(await verify(q,signature,client),{fee:5000,slot:123});});
 test("wrong network, non-finalized receipts and wrong mint are rejected",async()=>{const x=fixture();const wrong={...x.client,getGenesisHash:async()=>"wrong"} as unknown as Connection;await assert.rejects(()=>verify(x.q,x.signature,wrong));const pending={...x.client,getSignatureStatuses:async()=>({value:[{confirmationStatus:"confirmed",err:null}]})} as unknown as Connection;await assert.rejects(()=>verify(x.q,x.signature,pending));x.parsed.transaction.message.instructions[0].parsed.info.mint=Keypair.generate().publicKey.toBase58();await assert.rejects(()=>verify(x.q,x.signature,x.client));});
 test("a token transfer is not accepted as a verified burn",async()=>{const x=fixture();x.parsed.transaction.message.instructions[0].parsed.type="transferChecked";await assert.rejects(()=>verify(x.q,x.signature,x.client));});
 test("canonical USDC payment succeeds; altered message and amount fail",async()=>{const x=fixture("purchase");await verify(x.q,x.signature,x.client);x.q.message_hash="changed";await assert.rejects(()=>verify(x.q,x.signature,x.client));x.q.message_hash=hash(x.raw.transaction.message.serialize());x.parsed.transaction.message.instructions[0].parsed.info.tokenAmount.amount="999999";await assert.rejects(()=>verify(x.q,x.signature,x.client));});
