import test from "node:test";
import assert from "node:assert/strict";
import {database,row} from "../server/database";
import {Service} from "../server/service";
import {configuredModel,executeCustom,pricedCost} from "../server/custom-provider";
import {units} from "../server/money";
import {hash} from "../server/auth";
const config={LLM_MODEL_PROTOCOL:"openai-chat-sse",LLM_MODEL_CHAT_URL:"https://compute.example.test/v1/chat/completions",LLM_MODEL_API_KEY:"controlled-custom-endpoint-key",LLM_MODEL_ID:"owned-model-v1",LLM_MODEL_PROVIDER:"Self-hosted / vLLM",LLM_INPUT_USD_PER_MILLION:"0.4",LLM_OUTPUT_USD_PER_MILLION:"1.6",LLM_CONTEXT_TOKENS:"4096",LLM_MAX_OUTPUT_TOKENS:"1024"};
async function controlled(fn:()=>Promise<void>){const saved=Object.fromEntries(Object.keys(config).map(k=>[k,process.env[k]])),fetcher=globalThis.fetch;Object.assign(process.env,config);try{await fn();}finally{globalThis.fetch=fetcher;for(const [k,v]of Object.entries(saved))if(v===undefined)delete process.env[k];else process.env[k]=v;}}
function completion(model="owned-model-v1",usage=true){return new Response('data: '+JSON.stringify({id:"controlled-provider-request",model,choices:[{delta:{content:"OK"}}]})+'\n\n'+(usage?'data: '+JSON.stringify({id:"controlled-provider-request",model,choices:[],usage:{prompt_tokens:10,completion_tokens:2,total_tokens:12}})+'\n\n':"")+'data: [DONE]\n\n',{headers:{"Content-Type":"text/event-stream"}});}
const admin="controlled-custom-admin-key-more-than-32-characters";
function post(path:string,body:unknown,token=admin){return new Request("https://llm.example"+path,{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify(body)});}
function setup(){process.env.ADMIN_KEY=admin;const db=database(":memory:"),service=new Service(db);service.f.fund(units("10"),"controlled-funding","https://example.test/funds");service.f.configure(0,0,false);const q=service.f.quote("wallet","purchase","100000",units("0.1"));db.prepare("UPDATE quotes SET state='issued' WHERE id=?").run(q.id);service.f.receipt(q.id,"wallet","controlled-purchase");db.prepare("INSERT INTO api_keys(id,wallet,name,hash,created) VALUES('key','wallet','tool',?,?)").run(hash("llm_controlled"),Date.now());return service;}
test("custom catalog requires HTTPS, explicit protocol, exact prices and safe limits",()=>controlled(async()=>{assert.ok(configuredModel());for(const [key,value]of [["LLM_MODEL_PROTOCOL","unknown"],["LLM_MODEL_CHAT_URL","http://compute.example.test/v1/chat/completions"],["LLM_INPUT_USD_PER_MILLION","0.1e2"],["LLM_MAX_OUTPUT_TOKENS","999999"],["LLM_MODEL_API_KEY",""]]){const before=process.env[key];process.env[key]=value;assert.equal(configuredModel(),null);process.env[key]=before;}}));
test("custom pricing uses exact integers with deterministic rounding",()=>{assert.equal(pricedCost(10,2,units("0.4"),units("1.6")),7200);assert.equal(pricedCost(1,0,1,1),1);assert.throws(()=>pricedCost(1.1,1,1,1));assert.throws(()=>pricedCost(Number.MAX_SAFE_INTEGER,0,Number.MAX_SAFE_INTEGER,0));});
test("funding is required before a verification call and no legacy provider can activate the model",()=>controlled(async()=>{process.env.ADMIN_KEY=admin;const service=new Service(database(":memory:"));let calls=0;globalThis.fetch=async()=>{calls++;return completion();};assert.equal(service.providerReady(),false);assert.equal((await service.handle(post("/api/admin/provider/verify",{}))).status,503);assert.equal(calls,0);assert.equal(service.status().model.inputPerMillion,null);}));
test("verified custom streaming settles real normalized usage into shared credit lots",()=>controlled(async()=>{const service=setup();let calls=0;globalThis.fetch=async(input,init)=>{calls++;assert.equal(String(input),config.LLM_MODEL_CHAT_URL);assert.equal(init?.redirect,"error");assert.equal(new Headers(init?.headers).get("Authorization"),"Bearer "+config.LLM_MODEL_API_KEY);const b=JSON.parse(String(init?.body));assert.equal(b.model,"owned-model-v1");assert.equal(b.stream_options.include_usage,true);return completion();};const verify=await service.handle(post("/api/admin/provider/verify",{}));assert.equal(verify.status,200);assert.equal(service.providerReady(),true);assert.equal(service.status().model.name,"LocalLM");const before=service.f.available("wallet");const response=await service.handle(post("/api/v1/chat/completions",{model:"local-language-model",stream:true,max_tokens:16,messages:[{role:"user",content:"Hello"}]},"llm_controlled"));assert.equal(response.status,200);const output=await response.text();assert.match(output,/"content":"OK"/);assert.match(output,/\[DONE\]/);assert.match(output,/"charge":7200/);assert.equal(service.f.available("wallet"),before-7200);assert.equal(row<{spent:number}>(service.db,"SELECT spent FROM api_keys WHERE id='key'")!.spent,7200);assert.equal(calls,2);assert.equal(service.f.capacity().overhead,7200);const request=row<{input_price:number,output_price:number,model_id:string,state:string}>(service.db,"SELECT * FROM requests")!;assert.equal(request.input_price,units("0.4"));assert.equal(request.output_price,units("1.6"));assert.equal(request.model_id,"owned-model-v1");assert.equal(request.state,"settled");process.env.LLM_MODEL_API_KEY="different-controlled-endpoint-key";assert.equal(service.providerReady(),false);}));
test("identity mismatch or incomplete usage retains probe capacity and never opens model access",()=>controlled(async()=>{for(const response of [completion("wrong-model"),completion("owned-model-v1",false)]){const service=setup();globalThis.fetch=async()=>response;const before=service.f.capacity().free;assert.equal((await service.handle(post("/api/admin/provider/verify",{}))).status,502);assert.equal(service.providerReady(),false);assert.ok(service.f.capacity().free<before);assert.equal(service.f.available("wallet"),units("0.1"));}}));
test("uncertain request reconciliation honors its original prices after catalog changes",()=>controlled(async()=>{const service=setup();globalThis.fetch=async()=>completion();assert.equal((await service.handle(post("/api/admin/provider/verify",{}))).status,200);globalThis.fetch=async()=>completion("owned-model-v1",false);const response=await service.handle(post("/api/v1/chat/completions",{model:"local-language-model",stream:true,max_tokens:16,messages:[{role:"user",content:"Hi"}]},"llm_controlled"));await response.text();const request=row<{id:string,state:string}>(service.db,"SELECT * FROM requests")!;assert.equal(request.state,"uncertain");process.env.LLM_INPUT_USD_PER_MILLION="5";process.env.LLM_OUTPUT_USD_PER_MILLION="20";assert.equal(service.providerReady(),false);const settled=await service.handle(post("/api/admin/reconcile",{id:request.id,input:10,output:2,proof:"https://example.test/verified-usage"}));assert.equal(settled.status,200);assert.equal((await settled.json()).charge,7200);assert.equal(service.f.available("wallet"),units("0.1")-7200);const repeated=await service.handle(post("/api/admin/reconcile",{id:request.id,input:10,output:2,proof:"https://example.test/verified-usage"}));assert.equal(repeated.status,200);assert.equal(service.f.available("wallet"),units("0.1")-7200);}));
test("restart preserves an uncertain verification reserve until explicit evidence reconciliation",()=>controlled(async()=>{const service=setup(),model=configuredModel()!,maximum=100000;service.db.prepare("UPDATE budget SET overhead=overhead+?").run(maximum);service.db.prepare("INSERT INTO settings VALUES('provider_probe/restart',?)").run(JSON.stringify({state:"executing",maximum,inputPrice:model.inputPrice,outputPrice:model.outputPrice,created:Date.now()}));const restarted=new Service(service.db);assert.equal(restarted.f.capacity().overhead,maximum);assert.equal(JSON.parse(row<{value:string}>(service.db,"SELECT value FROM settings WHERE key='provider_probe/restart'")!.value).state,"uncertain");const result=await restarted.handle(post("/api/admin/provider/reconcile",{id:"restart",input:10,output:2,proof:"https://example.test/confirmed-probe"}));assert.equal(result.status,200);assert.equal(restarted.f.capacity().overhead,7200);assert.equal(restarted.providerReady(),false);assert.equal((await restarted.handle(post("/api/admin/provider/reconcile",{id:"restart",input:10,output:2,proof:"https://example.test/confirmed-probe"}))).status,409);}));
test("custom adapter rejects missing identity, invalid usage and redirects",()=>controlled(async()=>{const model=configuredModel()!;await assert.rejects(()=>executeCustom(model,[],8,()=>{},()=>false,async()=>new Response('data: {"id":"x","choices":[],"usage":{"prompt_tokens":1,"completion_tokens":1}}\n\ndata: [DONE]\n\n',{headers:{"Content-Type":"text/event-stream"}})));await assert.rejects(()=>executeCustom(model,[],8,()=>{},()=>false,async()=>new Response("moved",{status:302,headers:{location:"https://other.example/"}})));}));

test("adding price snapshots preserves legacy ledger entries and reconciliation rates",()=>controlled(async()=>{const service=setup();const id=service.f.reserve("wallet",100000,null,null);service.f.dispatched(id);assert.equal(service.f.request(id)!.input_price,null);assert.equal(row<{n:number}>(service.db,"SELECT COUNT(*) n FROM schema_migrations")!.n,5);const before=row<{n:number}>(service.db,"SELECT COUNT(*) n FROM ledger")!.n;process.env.LLM_INPUT_USD_PER_MILLION="5";const response=await service.handle(post("/api/admin/reconcile",{id,input:10,output:2,proof:"https://example.test/legacy-evidence"}));assert.equal(response.status,200);assert.equal((await response.json()).charge,7200);assert.ok(row<{n:number}>(service.db,"SELECT COUNT(*) n FROM ledger")!.n>before);assert.throws(()=>service.db.prepare("DELETE FROM ledger").run());}));
