import test from "node:test";
import assert from "node:assert/strict";
import {database,row} from "../server/database";
import {Service} from "../server/service";
import {Finance} from "../server/finance";
import {hash} from "../server/auth";
import {decimalUnits,exactJson} from "../server/exact-json";
import {hostedConfig,hostedModel,refreshHostedCatalog,refreshHostedBalance,executeHosted} from "../server/hosted-provider";
import {servingMessages,LOCAL_IDENTITY} from "../server/identity";
import {purchaseCredits,CREDIT_PACKAGES} from "../server/packages";
const env={LLM_MODEL_PROTOCOL:"hosted-credit-sse",HOSTED_API_BASE_URL:"https://private-serving.example/api/v1",HOSTED_API_KEY:"private-test-serving-secret",HOSTED_MODEL:"private-family/private-chat",LLM_MARKUP_BPS:"2000",LLM_CONTEXT_TOKENS:"4096",LLM_MAX_OUTPUT_TOKENS:"1024",ADMIN_KEY:"controlled-private-admin-key-over-32-characters",PUBLIC_URL:"https://llm.example"};
async function controlled(fn:()=>Promise<void>){const before=Object.fromEntries(Object.keys(env).map(k=>[k,process.env[k]])),oldFetch=globalThis.fetch;Object.assign(process.env,env);try{await fn();}finally{globalThis.fetch=oldFetch;for(const [k,v]of Object.entries(before))if(v===undefined)delete process.env[k];else process.env[k]=v;}}
function stream(cost=true,model=env.HOSTED_MODEL){return new Response('data: '+JSON.stringify({id:"private-generation-id",model,choices:[{delta:{content:"OK"}}]})+'\n\ndata: '+JSON.stringify({id:"private-generation-id",model,choices:[],usage:{prompt_tokens:10,completion_tokens:2,total_tokens:12,...(cost?{cost:0.0000072}:{}),is_byok:false}})+'\n\ndata: [DONE]\n\n',{headers:{"Content-Type":"text/event-stream"}});}
function mock(){let total=100,used=0,limit=100,extra=false,cost=true,model=env.HOSTED_MODEL;const bodies:any[]=[];globalThis.fetch=async(input,init)=>{const url=String(input);assert.equal(new Headers(init?.headers).get("Authorization"),"Bearer "+process.env.HOSTED_API_KEY);assert.equal(new Headers(init?.headers).get("X-Title"),null);if(url.endsWith("/credits"))return Response.json({data:{total_credits:total,total_usage:used}});if(url.endsWith("/key"))return Response.json({data:{limit_remaining:limit,is_free_tier:false,is_management_key:false}});if(url.includes("/endpoints"))return Response.json({data:{id:env.HOSTED_MODEL,endpoints:[{tag:"private-compute",provider_name:"Private Compute",model_id:env.HOSTED_MODEL,status:0,context_length:4096,max_completion_tokens:1024,max_prompt_tokens:4096,pricing:{prompt:"0.0000004",completion:"0.0000016",request:extra?"0.1":"0"}}]}});if(url.endsWith("/chat/completions")){bodies.push(JSON.parse(String(init?.body)));return stream(cost,model);}throw Error("Unexpected private transport call");};return {bodies,total:(n:number)=>total=n,used:(n:number)=>used=n,limit:(n:number)=>limit=n,extra:()=>extra=true,noCost:()=>cost=false,wrongModel:()=>model="another/model"};}
function post(path:string,b:unknown,token=env.ADMIN_KEY){return new Request("https://llm.example"+path,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify(b)});}
async function funded(){const service=new Service(database(":memory:"));await refreshHostedCatalog(service.db);const s=await refreshHostedBalance(service.db);service.f.stock(s.remaining,s.totalCredits,s.stockIdentity,"stock","https://llm.example/receipt",s.observedAt);service.f.configure(0,0,false);return service;}
test("exact provider decimals preserve numeric lexemes and round money conservatively",()=>{const v=exactJson('{"credit":0.1000000001,"tokens":12,"s":"123 \\"quoted\\"","exp":1e-7}');assert.equal(v.credit,"0.1000000001");assert.equal(v.tokens,"12");assert.equal(v.s,'123 "quoted"');assert.equal(decimalUnits(v.credit,9,"floor"),100000000);assert.equal(decimalUnits(v.credit,9,"ceil"),100000001);assert.equal(decimalUnits(v.exp),100);assert.throws(()=>decimalUnits("-1"));assert.throws(()=>decimalUnits("1e100"));assert.throws(()=>decimalUnits(0.1));assert.throws(()=>exactJson('{"n":01}'));});
test("only the exact 1 dollar launch package is accepted",()=>{for(const p of CREDIT_PACKAGES)assert.equal(purchaseCredits(BigInt(p.usdcAtomic)),p.credits);for(const amount of [1n,2000000n,5000000n,10000000n,20000000n,1000001n])assert.throws(()=>purchaseCredits(amount));});
test("private catalog uses exact verified flat rates and a deterministic service margin",()=>controlled(async()=>{const m=mock(),db=database(":memory:");const model=await refreshHostedCatalog(db);assert.equal(model.inputPrice,480000000);assert.equal(model.outputPrice,1920000000);assert.equal(model.markupBps,2000);assert.equal(hostedModel(db)?.upstreamModel,env.HOSTED_MODEL);m.extra();await assert.rejects(()=>refreshHostedCatalog(db));process.env.HOSTED_API_BASE_URL="http://private-serving.example/api/v1";assert.equal(hostedConfig(),null);}));
test("verified serving stock is imported once, topups are bounded and credential rotation cannot duplicate funding",()=>controlled(async()=>{const m=mock(),service=await funded();assert.equal(service.f.budget().cleared,100000000000);const snap=await refreshHostedBalance(service.db,true);assert.throws(()=>service.f.stock(snap.remaining,snap.totalCredits,snap.stockIdentity,"again","https://llm.example/receipt",snap.observedAt),/No new/);m.total(110);m.limit(110);const topup=await refreshHostedBalance(service.db,true);assert.equal(service.f.stock(topup.remaining,topup.totalCredits,topup.stockIdentity,"topup","https://llm.example/receipt",topup.observedAt).amount,10000000000);process.env.HOSTED_API_KEY="rotated-private-serving-key";const rotate=await refreshHostedBalance(service.db,true);assert.throws(()=>service.f.stock(rotate.remaining,rotate.totalCredits,rotate.stockIdentity,"rotate","https://llm.example/receipt",rotate.observedAt),/credentials changed/);assert.equal(service.f.budget().cleared,110000000000);}));
test("existing funding is preserved and cannot receive an unreconciled initial stock import",()=>controlled(async()=>{mock();const f=new Finance(database(":memory:"));f.fund(1000,"existing","https://llm.example/receipt");assert.throws(()=>f.stock(10000,10000,"identity","new","https://llm.example/receipt",Date.now()),/clean funding baseline/);assert.equal(f.budget().cleared,1000);}));
test("actual streaming protocol is pinned, privately configured and settled at public retail rates",()=>controlled(async()=>{const m=mock(),s=await funded();const probe=await s.handle(post("/api/admin/provider/verify",{}));assert.equal(probe.status,200,await probe.clone().text());assert.equal(s.providerReady(),true);assert.equal(s.f.capacity().overhead,7200);const q=s.f.quote("wallet","purchase","2000000",2000000000);s.db.prepare("UPDATE quotes SET state='issued' WHERE id=?").run(q.id);s.f.receipt(q.id,"wallet","controlled-finalized-receipt");s.db.prepare("INSERT INTO api_keys(id,wallet,name,hash,created) VALUES('key','wallet','tool',?,?)").run(hash("llm_private_test"),Date.now());const response=await s.handle(post("/api/v1/chat/completions",{model:"local-language-model",stream:true,max_tokens:16,messages:[{role:"system",content:"Client context"},{role:"user",content:"Hello"}]},"llm_private_test"));assert.equal(response.status,200,await response.clone().text());const output=await response.text();assert.match(output,/"charge":8640/);assert.match(output,/\[DONE\]/);assert.equal(s.f.available("wallet"),2000000000-8640);const r=row<any>(s.db,"SELECT * FROM requests")!;assert.equal(r.provider_cost,7200);assert.equal(r.model_id,env.HOSTED_MODEL);assert.equal(row<any>(s.db,"SELECT spent FROM api_keys WHERE id='key'")!.spent,8640);assert.equal(m.bodies[1].messages[0].role,"system");assert.match(m.bodies[1].messages[0].content,/LocalLM/);assert.equal(m.bodies[1].messages[1].role,"user");assert.deepEqual(m.bodies[1].provider.only,["private-compute"]);assert.equal(m.bodies[1].provider.allow_fallbacks,false);assert.equal(m.bodies[1].provider.zdr,true);assert.equal(m.bodies[1].provider.data_collection,"deny");assert.equal(m.bodies[1].provider.max_price.prompt,"0.40");const publicData=JSON.stringify(s.status())+output;for(const secret of [env.HOSTED_API_KEY,env.HOSTED_MODEL,env.HOSTED_API_BASE_URL,"private-generation-id","Private Compute"])assert.ok(!publicData.includes(secret));}));
test("missing actual cost or mismatched serving model retains capacity and blocks activation",()=>controlled(async()=>{for(const wrong of [false,true]){const m=mock(),s=await funded();if(wrong)m.wrongModel();else m.noCost();const before=s.f.capacity().free;const probe=await s.handle(post("/api/admin/provider/verify",{}));assert.equal(probe.status,502);assert.equal(s.providerReady(),false);assert.ok(s.f.capacity().free<before);}}));
test("external funding ceilings block quotes, daily grants and concurrent dispatch even with a funded local ledger",()=>controlled(async()=>{const m=mock(),s=await funded();s.f.lot("wallet","purchased",10000,"controlled");m.limit(0.000008);await refreshHostedBalance(s.db,true);const first=s.f.reserve("wallet",6000,null,null);assert.ok(first);assert.throws(()=>s.f.reserve("wallet",4000,null,null),/compute capacity/);assert.throws(()=>s.f.quote("other","burn","100",10000),/reserve/);s.f.configure(10000,0,false);assert.throws(()=>s.f.openEpoch("test",10000,1n,Date.now()+60000),/reserve/);m.limit(0);await refreshHostedBalance(s.db,true);assert.ok(s.f.capacity().free<0);}));
test("brand identity includes the real project inventory without leaking private model configuration",()=>controlled(async()=>{mock();const db=database(":memory:");const model=await refreshHostedCatalog(db),messages=servingMessages(model,[{role:"user",content:"Who are you?"}]);assert.match(LOCAL_IDENTITY,/four NVIDIA RTX 5090/);assert.match(LOCAL_IDENTITY,/128GB/);assert.match(messages[0].content,/LocalLM/);assert.ok(!messages[0].content.includes(model.upstreamModel));assert.ok(!messages[0].content.includes(model.key));assert.ok(!messages[0].content.includes(model.endpoint));}));

test("3.3x service rates back retail credits with exact provider funding and refuse a nineteenth one-dollar order",()=>controlled(async()=>{process.env.LLM_MARKUP_BPS="23000";const m=mock();m.total(5.7);m.limit(5.7);const s=await funded();assert.equal(s.f.capacity().cleared,5700000000);assert.equal(s.f.capacity().retailCapacity,18810000000);assert.equal(s.f.backing(1000000000),303030304);for(let i=0;i<18;i++)s.f.quote("retail-wallet-"+i,"purchase","1000000",1000000000);assert.throws(()=>s.f.quote("retail-wallet-19","purchase","1000000",1000000000),/reserve/);assert.equal(s.f.capacity().fundedQuoteReservations,5454545472);assert.equal(s.f.capacity().quoteReservations,18000000000);}));
test("retail usage and reported provider cost settle separately at 3.3x prices",()=>controlled(async()=>{process.env.LLM_MARKUP_BPS="23000";mock();const s=await funded();assert.equal((await s.handle(post("/api/admin/provider/verify",{}))).status,200);const q=s.f.quote("wallet","purchase","1000000",1000000000);s.db.prepare("UPDATE quotes SET state='issued' WHERE id=?").run(q.id);s.f.receipt(q.id,"wallet","controlled-one-dollar-receipt");s.db.prepare("INSERT INTO api_keys(id,wallet,name,hash,created) VALUES('key','wallet','tool',?,?)").run(hash("llm_price_test"),Date.now());const cleared=s.f.budget().cleared,response=await s.handle(post("/api/v1/chat/completions",{model:"local-language-model",stream:true,max_tokens:16,messages:[{role:"user",content:"Hello"}]},"llm_price_test"));assert.equal(response.status,200);assert.match(await response.text(),/"charge":23760/);assert.equal(s.f.available("wallet"),1000000000-23760);assert.equal(s.f.budget().cleared,cleared-7200);const r=row<any>(s.db,"SELECT * FROM requests")!;assert.equal(r.provider_cost,7200);assert.equal(r.funding_charge,7200);assert.equal(r.provider_input_price,400000000);assert.ok(r.funding_reservation<r.max_charge);assert.equal(r.state,"settled");}));
test("future buffer changes cannot confiscate previously issued credit capacity",()=>controlled(async()=>{process.env.LLM_MARKUP_BPS="23000";mock();const s=await funded();s.f.lot("wallet","purchased",1000000000,"controlled");s.f.configure(0,100000000000,true);assert.ok(s.f.capacity().free<0);assert.ok(s.f.reserve("wallet",10000,null,null));}));
test("automatic selection excludes free models and pins the lowest compatible verified rate",()=>controlled(async()=>{process.env.HOSTED_MODEL="auto-cheapest";const before=globalThis.fetch;const modelRecord=(id:string,prompt:string,completion:string)=>({id,context_length:4096,architecture:{input_modalities:["text"],output_modalities:["text"]},pricing:{prompt,completion,request:"0"}});globalThis.fetch=async(input)=>{const url=String(input);if(url.endsWith("/models"))return Response.json({data:[modelRecord("family/free","0","0"),modelRecord("family/cheap","0.0000001","0.0000002"),modelRecord("family/expensive","0.0000004","0.0000016")]});const id=url.includes("/cheap/")?"family/cheap":"family/expensive";return Response.json({data:{id,endpoints:[{tag:"verified",provider_name:"Private Compute",model_id:id,status:0,context_length:4096,max_completion_tokens:1024,max_prompt_tokens:4096,pricing:{prompt:id==="family/cheap"?"0.0000001":"0.0000004",completion:id==="family/cheap"?"0.0000002":"0.0000016",request:"0"}}]}});};const db=database(":memory:"),model=await refreshHostedCatalog(db);assert.equal(model.upstreamModel,"family/cheap");assert.equal(model.providerTag,"verified");assert.equal(model.inputPrice,120000000);globalThis.fetch=before;}));
