import {randomUUID} from "node:crypto";
import {row,rows,transaction,type DB} from "./database";
import {DAY,check,integer} from "./money";
import {hostedSelected,hostedSnapshot,hostedModel} from "./hosted-provider";
export type Budget={cleared:number,buffer:number,overhead:number,daily_limit:number,paused:number};
export type Lot={id:string,wallet:string,kind:string,available:number,reserved:number,expires:number|null,created:number};
export type Hold={wallet:string,balance:string,since:number,evidence_until:number,excluded:number};
export type Quote={id:string,wallet:string,kind:"purchase"|"burn",atomic_amount:string,credits:number,expires:number,state:string,message_hash:string|null,transaction_base64:string|null,reference:string|null,last_valid_height:number|null,blockhash:string|null,fee:number|null,signature:string|null,mint:string|null,decimals:number|null,recipient:string|null,created:number};
export type RequestRow={id:string,wallet:string,key_id:string|null,conversation:string|null,state:string,max_charge:number,charge:number,input:number|null,output:number|null,provider_id:string|null,provider_cost:number|null,funding_charge:number|null,funding_reservation:number|null,provider_input_price:number|null,provider_output_price:number|null,input_price:number|null,output_price:number|null,model_id:string|null,catalog_fingerprint:string|null,stop:number,created:number,updated:number};
export class Finance{
 constructor(public db:DB,public now=()=>Date.now()){}
 tx<T>(fn:()=>T){return transaction(this.db,fn);}
 event(wallet:string,kind:string,available:number,reserved:number,reference:string){this.db.prepare("INSERT INTO ledger(wallet,kind,available_delta,reserved_delta,reference,created) VALUES(?,?,?,?,?,?)").run(wallet,kind,available,reserved,reference,this.now());}
 expire(){const now=this.now();for(const lot of rows<Lot>(this.db,"SELECT * FROM lots WHERE expires<=? AND available>0",now)){this.db.prepare("UPDATE lots SET available=0 WHERE id=?").run(lot.id);this.event(lot.wallet,"expiration",-lot.available,0,lot.id);}this.db.prepare("UPDATE epochs SET remaining=0 WHERE deadline<=?").run(now);}
 budget(){return row<Budget>(this.db,"SELECT * FROM budget WHERE id=1")!;}
 backing(retail:number){integer(retail);if(!hostedSelected())return retail;const markup=hostedModel(this.db)?.markupBps??0;return Number((BigInt(retail)*10000n+BigInt(9999+markup))/BigInt(10000+markup));}
 providerFunds(snapshot:NonNullable<ReturnType<typeof hostedSnapshot>>){let active=0,cachedProbes=0;for(const record of rows<{value:string}>(this.db,"SELECT value FROM settings WHERE key LIKE 'provider_probe/%'")){try{const p=JSON.parse(record.value);if(p.state==="executing"||p.state==="uncertain")active+=p.fundMaximum??p.maximum;if(p.state==="settled"&&p.created>=snapshot.observedAt)cachedProbes+=p.charge;}catch{}}const cachedRequests=row<{n:number}>(this.db,"SELECT COALESCE(SUM(COALESCE(funding_charge,provider_cost,charge)),0) n FROM requests WHERE state='settled' AND updated>=?",snapshot.observedAt)!.n;return snapshot.remaining-active-cachedProbes-cachedRequests;}
 capacity(){const b=this.budget();const lotRows=rows<{n:number}>(this.db,"SELECT available+reserved n FROM lots"),epochRows=rows<{n:number}>(this.db,"SELECT remaining n FROM epochs"),quoteRows=rows<{n:number}>(this.db,"SELECT credits n FROM quotes WHERE state IN ('open','issued')");const sum=(items:{n:number}[])=>items.reduce((n,x)=>n+x.n,0),backed=(items:{n:number}[])=>items.reduce((n,x)=>n+this.backing(x.n),0),lots=sum(lotRows),epochs=sum(epochRows),quotes=sum(quoteRows),fundedLots=backed(lotRows),fundedEpochs=backed(epochRows),fundedQuotes=backed(quoteRows),localFree=b.cleared-b.buffer-b.overhead-fundedLots-fundedEpochs-fundedQuotes,snapshot=hostedSnapshot(this.db),providerFree=snapshot?this.providerFunds(snapshot)-b.buffer-fundedLots-fundedEpochs-fundedQuotes:0,free=hostedSelected()?Math.min(localFree,providerFree):localFree,markup=hostedModel(this.db)?.markupBps??0;const retailCapacity=free>0?Number(BigInt(free)*BigInt(10000+markup)/10000n):0;check(Number.isSafeInteger(retailCapacity),"Capacity exceeds accounting limit",503);return {cleared:b.cleared,buffer:b.buffer,overhead:b.overhead,obligations:lots,epochReservations:epochs,quoteReservations:quotes,fundedObligations:fundedLots,fundedEpochReservations:fundedEpochs,fundedQuoteReservations:fundedQuotes,free,retailCapacity,dailyLimit:b.daily_limit,paused:!!b.paused,computeFunding:hostedSelected()?{remaining:snapshot?.remaining??null,observedAt:snapshot?.observedAt??null,status:snapshot?"verified":"unavailable"}:null};}
 executionCapacity(max:number){if(!hostedSelected())return;const snapshot=hostedSnapshot(this.db);check(snapshot,"Compute funding balance must be verified before dispatch",503);const pending=row<{n:number}>(this.db,"SELECT COALESCE(SUM(COALESCE(funding_reservation,max_charge)),0) n FROM requests WHERE state IN ('reserved','executing','uncertain')")!.n,b=this.budget();check(Math.min(b.cleared-b.overhead,this.providerFunds(snapshot))-pending>=this.backing(max),"Insufficient verified compute capacity",503);}


 fund(amount:number,reference:string,proof:string){return this.tx(()=>{check(integer(amount)>0,"Funding must be positive");check(!row(this.db,"SELECT reference FROM funds WHERE reference=?",reference),"Funding reference already recorded",409);check(this.budget().cleared+amount<=Number.MAX_SAFE_INTEGER,"Funding limit exceeded");this.db.prepare("INSERT INTO funds VALUES(?,?,?,?)").run(reference,amount,proof,this.now());this.db.prepare("UPDATE budget SET cleared=cleared+? WHERE id=1").run(amount);return this.capacity();});}
 stock(remaining:number,totalCredits:number,identity:string,reference:string,proof:string,observedAt:number){return this.tx(()=>{integer(remaining);integer(totalCredits);const previous=row<{value:string}>(this.db,"SELECT value FROM settings WHERE key='serving_stock'");let amount:number;if(previous){const p=JSON.parse(previous.value);check(p.identity===identity,"Serving credentials changed; reconcile funding before importing further stock",409);check(totalCredits>=p.totalCredits,"Serving funding counter moved backwards; reconciliation required",409);amount=Math.min(totalCredits-p.totalCredits,remaining);}else{check(row<{n:number}>(this.db,"SELECT COUNT(*) n FROM funds")!.n===0&&this.budget().cleared===0,"Initial stock import requires a clean funding baseline; preserve and reconcile existing funds",409);amount=remaining;}check(amount>0,"No new cleared serving credits to import",409);check(this.budget().cleared+amount<=Number.MAX_SAFE_INTEGER,"Funding limit exceeded");this.db.prepare("INSERT INTO funds VALUES(?,?,?,?)").run(reference,amount,proof,this.now());this.db.prepare("UPDATE budget SET cleared=cleared+? WHERE id=1").run(amount);this.db.prepare("INSERT INTO settings VALUES('serving_stock',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify({identity,totalCredits,observedAt}));this.db.prepare("INSERT INTO settings VALUES(?,?)").run("fund_evidence/"+reference,JSON.stringify({reference,amount,observedAt,method:"verified_serving_credit_balance"}));return {amount,reference,capacity:this.capacity()};});}

 configure(daily:number,buffer:number,paused:boolean){return this.tx(()=>{integer(daily);integer(buffer);this.db.prepare("UPDATE budget SET daily_limit=?,buffer=?,paused=? WHERE id=1").run(daily,buffer,Number(paused));return this.capacity();});}
 available(wallet:string){return row<{n:number}>(this.db,"SELECT COALESCE(SUM(available),0) n FROM lots WHERE wallet=? AND (expires IS NULL OR expires>?)",wallet,this.now())!.n;}
 lot(wallet:string,kind:"daily"|"purchased"|"burn",amount:number,ref:string){integer(amount);const id=randomUUID(),now=this.now();this.db.prepare("INSERT INTO lots(id,wallet,kind,available,expires,created) VALUES(?,?,?,?,?,?)").run(id,wallet,kind,amount,kind==="daily"?now+DAY:null,now);this.event(wallet,kind==="daily"?"daily_grant":kind==="purchased"?"purchase":"burn_redemption",amount,0,ref);return id;}
 observe(wallet:string,balance:bigint,evidence:number,excluded=false){const h=row<Hold>(this.db,"SELECT * FROM holds WHERE wallet=?",wallet);check(balance>=0n,"Invalid holding");const since=!h||balance>BigInt(h.balance)?evidence:h.since;this.db.prepare("INSERT INTO holds VALUES(?,?,?,?,?) ON CONFLICT(wallet) DO UPDATE SET balance=excluded.balance,since=excluded.since,evidence_until=excluded.evidence_until,excluded=excluded.excluded").run(wallet,balance.toString(),since,evidence,Number(excluded));}
 openEpoch(id:string,pool:number,minimum:bigint,deadline:number){return this.tx(()=>{this.expire();check(minimum>0n,"A validated minimum holding is required");check(integer(pool)>0,"Daily pool must be positive");check(!this.budget().paused,"New grants are paused",503);check(pool<=this.budget().daily_limit,"Pool exceeds daily budget");check(this.capacity().free>=this.backing(pool),"Insufficient cleared reserve",503);check(deadline>this.now()&&deadline<=this.now()+DAY,"Invalid claim deadline");check(!row(this.db,"SELECT id FROM epochs WHERE id=?",id),"Epoch is already frozen",409);const eligible=rows<Hold>(this.db,"SELECT * FROM holds WHERE excluded=0 AND since<=evidence_until-? AND evidence_until>=?",DAY,this.now()-120_000).filter(h=>BigInt(h.balance)>=minimum);check(eligible.length>0&&eligible.length<=1000,"No proven eligible holder set");const total=eligible.reduce((n,h)=>n+BigInt(h.balance),0n);const allocations=eligible.map(h=>({wallet:h.wallet,amount:Number(BigInt(pool)*BigInt(h.balance)/total)}));const allocated=allocations.reduce((n,x)=>n+x.amount,0);this.db.prepare("INSERT INTO epochs VALUES(?,?,?,?,?)").run(id,pool,allocated,deadline,this.now());for(const a of allocations)this.db.prepare("INSERT INTO allocations(epoch,wallet,amount) VALUES(?,?,?)").run(id,a.wallet,a.amount);return allocations;});}
 claim(wallet:string,epoch:string){return this.tx(()=>{this.expire();const a=row<{amount:number,claimed:number,deadline:number}>(this.db,"SELECT a.*,e.deadline FROM allocations a JOIN epochs e ON e.id=a.epoch WHERE a.wallet=? AND a.epoch=?",wallet,epoch);check(a&&a.amount>0,"Wallet is ineligible for this frozen epoch",403);check(a.deadline>this.now(),"Claim deadline passed");check(!a.claimed,"Already claimed this epoch",409);this.db.prepare("UPDATE allocations SET claimed=1 WHERE wallet=? AND epoch=? AND claimed=0").run(wallet,epoch);this.db.prepare("UPDATE epochs SET remaining=remaining-? WHERE id=?").run(a.amount,epoch);const id=this.lot(wallet,"daily",a.amount,epoch);return {amount:a.amount,expires:row<Lot>(this.db,"SELECT * FROM lots WHERE id=?",id)!.expires};});}
 purchaseStock(){const value=process.env.PURCHASE_ORDER_LIMIT;if(value===undefined||value==="")return null;check(/^\d{1,7}$/.test(value)&&Number(value)>0&&Number(value)<=1000000,"Invalid checkout inventory limit",503);const limit=Number(value),sold=row<{n:number}>(this.db,"SELECT COUNT(*) n FROM receipts WHERE kind='purchase'")!.n,reserved=row<{n:number}>(this.db,"SELECT COUNT(*) n FROM quotes WHERE kind='purchase' AND state IN ('open','issued')")!.n;return {limit,sold,reserved,remaining:Math.max(0,limit-sold-reserved),exhausted:sold+reserved>=limit};}
 quote(wallet:string,kind:"purchase"|"burn",atomic:string,credits:number){return this.tx(()=>{this.expire();check(!this.budget().paused,"New quotes are paused",503);check(integer(credits)>0,"Quote must issue positive credits");if(kind==="purchase"){const stock=this.purchaseStock();check(!stock||!stock.exhausted,"This credit batch is sold out. More credits will be added soon",503);}check(this.capacity().free>=this.backing(credits),"Insufficient cleared reserve",503);check(rows(this.db,"SELECT id FROM quotes WHERE wallet=? AND state IN ('open','issued')",wallet).length<3,"Account quote limit reached",429);check(row<{n:number}>(this.db,"SELECT COUNT(*) n FROM quotes WHERE wallet=? AND created>?",wallet,this.now()-60000)!.n<12,"Quote frequency limit reached",429);check(rows(this.db,"SELECT id FROM quotes WHERE state IN ('open','issued')").length<100,"Quote capacity reached",429);const q={id:randomUUID(),wallet,kind,atomic_amount:atomic,credits,expires:this.now()+60_000};this.db.prepare("INSERT INTO quotes(id,wallet,kind,atomic_amount,credits,expires,created) VALUES(?,?,?,?,?,?,?)").run(q.id,wallet,kind,atomic,credits,q.expires,this.now());return row<Quote>(this.db,"SELECT * FROM quotes WHERE id=?",q.id)!;});}
 receipt(id:string,wallet:string,signature:string){return this.tx(()=>{const q=row<Quote>(this.db,"SELECT * FROM quotes WHERE id=? AND wallet=?",id,wallet);check(q,"Unknown quote",404);const receipt=row<{quote:string}>(this.db,"SELECT * FROM receipts WHERE signature=?",signature);if(receipt){check(receipt.quote===id,"Receipt already used by another order",409);return {credits:q.credits,duplicate:true};}check(q.state==="issued","Quote is not backed by a valid reserved transaction",409);this.db.prepare("INSERT INTO receipts VALUES(?,?,?,?,?,?)").run(signature,id,q.kind,wallet,q.credits,this.now());this.db.prepare("UPDATE quotes SET state='settled',signature=? WHERE id=?").run(signature,id);this.lot(wallet,q.kind==="purchase"?"purchased":"burn",q.credits,id);return {credits:q.credits,duplicate:false};});}
 reserve(wallet:string,max:number,keyId:string|null,conversation:string|null,pricing?:{inputPrice:number,outputPrice:number,modelId:string,fingerprint:string,providerInputPrice?:number,providerOutputPrice?:number}){return this.tx(()=>{this.expire();check(integer(max)>0,"Positive reservation required");check(this.available(wallet)>=max,"Insufficient credits for maximum request charge",402);this.executionCapacity(max);check(row<{n:number}>(this.db,"SELECT COUNT(*) n FROM requests WHERE state IN ('reserved','executing','uncertain')")!.n<8,"Service concurrency limit reached",429);check(row<{n:number}>(this.db,"SELECT COUNT(*) n FROM requests WHERE wallet=? AND state IN ('reserved','executing','uncertain')",wallet)!.n<2,"Account concurrency limit reached",429);check(row<{n:number}>(this.db,"SELECT COUNT(*) n FROM requests WHERE wallet=? AND created>?",wallet,this.now()-60_000)!.n<12,"Request frequency limit reached",429);if(keyId){const k=row<{cap:number|null,spent:number,reserved:number,revoked:number}>(this.db,"SELECT * FROM api_keys WHERE id=? AND wallet=?",keyId,wallet);check(k&&!k.revoked,"API key is revoked",401);check(k.cap===null||k.spent+k.reserved+max<=k.cap,"API key spending cap reached",402);this.db.prepare("UPDATE api_keys SET reserved=reserved+?,last_used=? WHERE id=?").run(max,this.now(),keyId);}const id=randomUUID();this.db.prepare("INSERT INTO requests(id,wallet,key_id,conversation,state,max_charge,created,updated) VALUES(?,?,?,?,'reserved',?,?,?)").run(id,wallet,keyId,conversation,max,this.now(),this.now());this.db.prepare("UPDATE requests SET funding_reservation=? WHERE id=?").run(this.backing(max),id);if(pricing){integer(pricing.inputPrice);integer(pricing.outputPrice);this.db.prepare("UPDATE requests SET input_price=?,output_price=?,model_id=?,catalog_fingerprint=? WHERE id=?").run(pricing.inputPrice,pricing.outputPrice,pricing.modelId,pricing.fingerprint,id);}if(pricing?.providerInputPrice!==undefined&&pricing?.providerOutputPrice!==undefined)this.db.prepare("UPDATE requests SET provider_input_price=?,provider_output_price=? WHERE id=?").run(integer(pricing.providerInputPrice),integer(pricing.providerOutputPrice),id);let remaining=max;for(const lot of rows<Lot>(this.db,"SELECT * FROM lots WHERE wallet=? AND available>0 AND (expires IS NULL OR expires>?) ORDER BY expires IS NULL,expires,created",wallet,this.now())){if(!remaining)break;const n=Math.min(remaining,lot.available);this.db.prepare("UPDATE lots SET available=available-?,reserved=reserved+? WHERE id=?").run(n,n,lot.id);this.db.prepare("INSERT INTO reservations VALUES(?,?,?)").run(id,lot.id,n);remaining-=n;}check(remaining===0,"Reservation invariant failed",500);this.event(wallet,"request_reservation",-max,max,id);return id;});}
 dispatched(id:string){const result=this.db.prepare("UPDATE requests SET state='executing',updated=? WHERE id=? AND state='reserved'").run(this.now(),id);check(Number(result.changes)===1,"Request reservation is no longer available",409);}
 request(id:string){return row<RequestRow>(this.db,"SELECT * FROM requests WHERE id=?",id);}
 settle(id:string,charge:number,input:number,output:number,providerId:string,proof:string|null=null,providerCost:number|null=null){return this.tx(()=>{const r=this.request(id);check(r,"Unknown request",404);if(r.state==="settled")return r;check(["executing","uncertain"].includes(r.state),"Request cannot be settled",409);check(integer(charge)<=r.max_charge,"Provider usage exceeds reserved charge",409);integer(input);integer(output);const fundingCharge=providerCost!==null?integer(providerCost):r.provider_input_price!==null&&r.provider_output_price!==null?Number((BigInt(input)*BigInt(r.provider_input_price)+BigInt(output)*BigInt(r.provider_output_price)+999999n)/1000000n):charge;check(fundingCharge<=charge&&fundingCharge<=(r.funding_reservation??r.max_charge),"Provider cost exceeds held funding; usage reconciliation required",409);let remaining=charge;let released=0;let expired=0;for(const x of rows<{lot:string,amount:number,expires:number|null}>(this.db,"SELECT r.lot,r.amount,l.expires FROM reservations r JOIN lots l ON l.id=r.lot WHERE r.request=? ORDER BY l.expires IS NULL,l.expires,l.created",id)){const spent=Math.min(remaining,x.amount);remaining-=spent;const refund=x.amount-spent;const isExpired=x.expires!==null&&x.expires<=this.now();if(isExpired)expired+=refund;else released+=refund;this.db.prepare("UPDATE lots SET reserved=reserved-?,available=available+? WHERE id=?").run(x.amount,isExpired?0:refund,x.lot);}check(remaining===0,"Settlement invariant failed",500);this.event(r.wallet,"usage_settlement",0,-charge,id);if(released)this.event(r.wallet,"refund_release",released,-released,id);if(expired)this.event(r.wallet,"expiration",0,-expired,id);this.db.prepare("UPDATE budget SET cleared=cleared-? WHERE id=1").run(fundingCharge);if(r.key_id)this.db.prepare("UPDATE api_keys SET reserved=reserved-?,spent=spent+? WHERE id=?").run(r.max_charge,charge,r.key_id);this.db.prepare("UPDATE requests SET state='settled',charge=?,input=?,output=?,provider_id=?,proof=?,provider_cost=?,funding_charge=?,updated=? WHERE id=?").run(charge,input,output,providerId,proof,providerCost,fundingCharge,this.now(),id);return this.request(id)!;});}
 releaseUndispatched(id:string){const r=this.request(id);check(r?.state==="reserved","Dispatched requests cannot receive an unearned refund",409);for(const x of rows<{lot:string,amount:number,expires:number|null}>(this.db,"SELECT r.lot,r.amount,l.expires FROM reservations r JOIN lots l ON l.id=r.lot WHERE r.request=?",id)){const expires=x.expires!==null&&x.expires<=this.now();this.db.prepare("UPDATE lots SET reserved=reserved-?,available=available+? WHERE id=?").run(x.amount,expires?0:x.amount,x.lot);this.event(r.wallet,expires?"expiration":"refund_release",expires?0:x.amount,-x.amount,id);}if(r.key_id)this.db.prepare("UPDATE api_keys SET reserved=reserved-? WHERE id=?").run(r.max_charge,r.key_id);this.db.prepare("UPDATE requests SET state='released',updated=? WHERE id=?").run(this.now(),id);}
 recover(restart=false){return this.tx(()=>{this.expire();for(const r of rows<RequestRow>(this.db,"SELECT * FROM requests WHERE state='reserved' AND updated<?",restart?this.now()+1:this.now()-120_000))this.releaseUndispatched(r.id);this.db.prepare("UPDATE requests SET state='uncertain',updated=? WHERE state='executing' AND updated<?").run(this.now(),restart?this.now()+1:this.now()-120_000);this.db.prepare("UPDATE quotes SET state='released' WHERE state='open' AND expires<?").run(this.now());});}
}
