import {createHash} from "node:crypto";
import {row,type DB} from "./database";
import {check,money} from "./money";
import {decimalUnits,exactInteger,exactJson,providerJson} from "./exact-json";
import type {CustomModel} from "./custom-provider";
import type {Message,Usage} from "./provider";
export const hostedSelected=()=>process.env.LLM_MODEL_PROTOCOL==="hosted-credit-sse";
export function hostedConfig(){if(!hostedSelected())return null;const base=process.env.HOSTED_API_BASE_URL,key=process.env.HOSTED_API_KEY,model=process.env.HOSTED_MODEL,tag=process.env.HOSTED_PROVIDER_TAG??"",markup=process.env.LLM_MARKUP_BPS??"2000";if(!base||!key||key.length<16||key.length>1024||/[\r\n]/.test(key)||!model||! /^[a-zA-Z0-9_.-]{1,80}\/[a-zA-Z0-9_.:-]{1,160}$/.test(model)||!/^\d{1,5}$/.test(markup)||Number(markup)>10000||! /^[a-zA-Z0-9_./:-]{0,120}$/.test(tag))return null;let baseUrl:URL;try{baseUrl=new URL(base);if(baseUrl.protocol!=="https:"||baseUrl.username||baseUrl.password||baseUrl.search||baseUrl.hash||!baseUrl.pathname.endsWith("/api/v1"))return null;}catch{return null;}const context=Number(process.env.LLM_CONTEXT_TOKENS??32768),maxOutput=Number(process.env.LLM_MAX_OUTPUT_TOKENS??4096);if(!Number.isInteger(context)||context<2048||context>131072||!Number.isInteger(maxOutput)||maxOutput<8||maxOutput>4096||maxOutput>=context-1024)return null;const fingerprint=createHash("sha256").update(JSON.stringify([base,key,model,tag,markup,context,maxOutput,"zdr-deny-pinned"])).digest("hex");return {base,key,model,tag,markup:Number(markup),context,maxOutput,fingerprint};}
type Catalog={configFingerprint:string,model:string,allowedIds:string[],tag:string,providerName:string,inputPrice:number,outputPrice:number,baseInput:number,baseOutput:number,context:number,maxOutput:number,markup:number,observedAt:number};
type Snapshot={configFingerprint:string,stockIdentity:string,totalCredits:number,remaining:number,accountRemaining:number,keyRemaining:number|null,observedAt:number};
const headers=(key:string)=>({"Authorization":"Bearer "+key,Accept:"application/json"});
const request=(url:string,key:string)=>fetch(url,{headers:headers(key),redirect:"error",signal:AbortSignal.timeout(7000)});
export function hostedModel(db:DB):CustomModel|null{const cfg=hostedConfig();if(!cfg)return null;const record=row<{value:string}>(db,"SELECT value FROM settings WHERE key='hosted_catalog'");if(!record)return null;try{const c=JSON.parse(record.value) as Catalog;if(c.configFingerprint!==cfg.fingerprint||Date.now()-c.observedAt>=86400000||c.observedAt>Date.now())return null;return {endpoint:cfg.base+"/chat/completions",key:cfg.key,upstreamModel:c.model,provider:c.providerName,inputPrice:c.inputPrice,outputPrice:c.outputPrice,context:c.context,maxOutput:c.maxOutput,fingerprint:createHash("sha256").update(JSON.stringify(c)).digest("hex"),transport:"hosted-credit-sse",providerTag:c.tag,allowedModelIds:c.allowedIds,providerInputPrice:c.baseInput,providerOutputPrice:c.baseOutput,markupBps:c.markup,pricingObservedAt:c.observedAt};}catch{return null;}}
export function hostedSnapshot(db:DB){const cfg=hostedConfig();if(!cfg)return null;const record=row<{value:string}>(db,"SELECT value FROM settings WHERE key='hosted_balance'");if(!record)return null;try{const s=JSON.parse(record.value) as Snapshot;return s.configFingerprint===cfg.fingerprint&&Number.isSafeInteger(s.remaining)&&s.remaining>=0&&s.observedAt<=Date.now()&&Date.now()-s.observedAt<30000?s:null;}catch{return null;}}
const pending=new WeakMap<DB,Promise<Snapshot>>();
export async function refreshHostedBalance(db:DB,force=false){const cfg=hostedConfig();check(cfg,"Configure Hosted inference credentials and model first",503);const current=hostedSnapshot(db);if(!force&&current&&Date.now()-current.observedAt<5000)return current;const inflight=pending.get(db);if(inflight)return inflight;
const promise=(async()=>{try{const results=await Promise.allSettled([request(cfg.base+"/credits",cfg.key).then(r=>providerJson(r,65536)),request(cfg.base+"/key",cfg.key).then(r=>providerJson(r,65536))]);for(const r of results)check(r.status==="fulfilled","Hosted inference balance could not be verified",503);const credits=(results[0] as PromiseFulfilledResult<any>).value.data,key=(results[1] as PromiseFulfilledResult<any>).value.data;check(credits&&key&&!key.is_management_key&&!key.is_free_tier,"A paid inference key is required",503);const totalCredits=decimalUnits(credits.total_credits,9,"floor"),stockIdentity=createHash("sha256").update(cfg.base+"\n"+cfg.key).digest("hex");const accountRemaining=Math.max(0,totalCredits-decimalUnits(credits.total_usage,9,"ceil"));const keyRemaining=key.limit_remaining===null?null:decimalUnits(key.limit_remaining,9,"floor");const snapshot={configFingerprint:cfg.fingerprint,stockIdentity,totalCredits,remaining:keyRemaining===null?accountRemaining:Math.min(accountRemaining,keyRemaining),accountRemaining,keyRemaining,observedAt:Date.now()};db.prepare("INSERT INTO settings VALUES('hosted_balance',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify(snapshot));return snapshot;}catch(e){db.prepare("DELETE FROM settings WHERE key='hosted_balance'").run();throw e;}})();pending.set(db,promise);try{return await promise;}finally{pending.delete(db);}}
export async function refreshHostedCatalog(db:DB){const cfg=hostedConfig();check(cfg,"Configure HOSTED_API_KEY, HOSTED_MODEL and limits",503);const [author,slug]=cfg.model.split("/");const response=await request(cfg.base+"/models/"+encodeURIComponent(author)+"/"+encodeURIComponent(slug)+"/endpoints",cfg.key);const {data}=await providerJson(response);check(data&&data.id===cfg.model&&Array.isArray(data.endpoints)&&data.endpoints.length<=256,"Hosted inference model catalog did not match",503);
 const eligible:Catalog[]=[];for(const e of data.endpoints){try{if(cfg.tag&&e.tag!==cfg.tag)continue;if(e.status!==undefined&&e.status!=="0")continue;check(typeof e.tag==="string"&&/^[a-zA-Z0-9_./:-]{1,120}$/.test(e.tag)&&typeof e.provider_name==="string"&&e.provider_name.length<=100,"Invalid provider endpoint");const p=e.pricing;check(p&&(!p.overrides||p.overrides.length===0),"Dynamic pricing requires a separate adapter");for(const name of ["request","internal_reasoning","input_cache_write","input_cache_write_1h"])if(p[name]!==undefined)check(decimalUnits(p[name],15)===0,"Additional provider charges are unsupported");const baseInput=decimalUnits(p.prompt,15),baseOutput=decimalUnits(p.completion,15);check(baseInput>0&&baseOutput>0,"Paid text pricing required");const context=Math.min(cfg.context,exactInteger(e.context_length)),maxOutput=Math.min(cfg.maxOutput,e.max_completion_tokens===null?cfg.maxOutput:exactInteger(e.max_completion_tokens),context-1025);check(context>=2048&&maxOutput>=8,"Model limits are too small");const promptLimit=e.max_prompt_tokens===null?context:exactInteger(e.max_prompt_tokens);const boundedContext=Math.min(context,promptLimit+maxOutput);check(boundedContext>maxOutput+1024,"Invalid prompt limit");const marked=(n:number)=>{const value=(BigInt(n)*BigInt(10000+cfg.markup)+9999n)/10000n;check(value<=BigInt(Number.MAX_SAFE_INTEGER),"Retail rate exceeds accounting limit");return Number(value);};const allowedIds=[cfg.model];if(typeof e.model_id==="string"&&e.model_id.length<=200)allowedIds.push(e.model_id);eligible.push({configFingerprint:cfg.fingerprint,model:cfg.model,allowedIds:[...new Set(allowedIds)],tag:e.tag,providerName:e.provider_name,inputPrice:marked(baseInput),outputPrice:marked(baseOutput),baseInput,baseOutput,context:boundedContext,maxOutput,markup:cfg.markup,observedAt:Date.now()});}catch{continue;}}
check(eligible.length,"No compatible flat-priced endpoint exists for this model/provider",503);eligible.sort((a,b)=>{const left=BigInt(a.baseInput)+BigInt(a.baseOutput),right=BigInt(b.baseInput)+BigInt(b.baseOutput);return left<right?-1:left>right?1:a.tag.localeCompare(b.tag);});db.prepare("INSERT INTO settings VALUES('hosted_catalog',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify(eligible[0]));return hostedModel(db)!;
}
export async function executeHosted(model:CustomModel,messages:Message[],maxOutput:number,onToken:(text:string)=>void,stopped:()=>boolean):Promise<Usage>{check(model.transport==="hosted-credit-sse"&&model.providerTag&&model.providerInputPrice&&model.providerOutputPrice,"Verified Hosted inference catalog is required",503);
 const response=await fetch(model.endpoint,{method:"POST",headers:{...headers(model.key),"Content-Type":"application/json",Accept:"text/event-stream"},body:JSON.stringify({model:model.upstreamModel,messages,max_tokens:maxOutput,stream:true,usage:{include:true},provider:{only:[model.providerTag],order:[model.providerTag],allow_fallbacks:false,require_parameters:true,data_collection:"deny",zdr:true,max_price:{prompt:money(model.providerInputPrice).slice(1),completion:money(model.providerOutputPrice).slice(1),request:"0"}}}),redirect:"error",signal:AbortSignal.timeout(45000)});
 check(response.ok&&response.body&&response.headers.get("content-type")?.includes("text/event-stream"),"Hosted inference execution requires reconciliation",502);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="",done=false,modelSeen=false,id="",usage:Usage|undefined,total=0;
 try{while(true){const next=await reader.read();if(next.done)break;buffer+=decoder.decode(next.value,{stream:true});check(buffer.length<262144,"Provider frame exceeds limit",502);let end;while((end=buffer.indexOf("\n"))>=0){const line=buffer.slice(0,end).trim();buffer=buffer.slice(end+1);if(!line.startsWith("data:"))continue;const raw=line.slice(5).trim();if(raw==="[DONE]"){check(!done,"Duplicate provider termination",502);done=true;continue;}check(!done&&!stopped(),"Provider request requires reconciliation",502);const data=exactJson(raw);check(!data.error,"Provider returned an error",502);if(data.model!==undefined){check(model.allowedModelIds?.includes(data.model),"Provider model identity changed",502);modelSeen=true;}if(data.id!==undefined){check(typeof data.id==="string"&&data.id.length>0&&data.id.length<=200&&!/[\x00-\x1f]/.test(data.id),"Invalid provider request identifier",502);check(!id||id===data.id,"Provider request identifier changed",502);id=data.id;}const content=data.choices?.[0]?.delta?.content;if(content!==undefined&&content!==null){check(typeof content==="string","Unsupported provider content",502);total+=new TextEncoder().encode(content).length;check(total<=262144,"Provider output exceeds limit",502);onToken(content);}
 if(data.usage){const input=exactInteger(data.usage.prompt_tokens),output=exactInteger(data.usage.completion_tokens);check(input+output<=model.context&&output<=maxOutput,"Provider usage exceeds limits",502);check(exactInteger(data.usage.total_tokens)===input+output,"Provider usage is inconsistent",502);check(data.usage.is_byok!==true,"BYOK cost accounting is not configured",502);const providerCost=decimalUnits(data.usage.cost,9,"ceil");if(usage)check(usage.input===input&&usage.output===output&&usage.providerCost===providerCost,"Provider usage changed",502);usage={input,output,providerId:id,providerCost};}
 }}check(buffer.trim()===""&&done&&usage&&modelSeen&&id,"Provider stream ended without complete identity, usage and cost",502);return {...usage,providerId:id};}finally{await reader.cancel().catch(()=>{});}
}
