import {useEffect,useState} from "react";
import {accountReadings,count,vram} from "./compute-data";
import {BrandSymbol,SocialControls} from "./social";
type Props={me:any;status:any;accountState:string;connect:()=>void};
type Network={status:string;inferenceConnected:boolean;telemetryStatus:string;observedAt:string|null;source:string|null;metrics:{gpusOnline:number|null;aggregateVramBytes:string|null;requestsServed:string|null;tokensGenerated:string|null;utilizationBps:number|null;modelVersion:string|null};architecture:{id:string;label:string;state:string;detail:string}[]};
const stages=[["user","USER","Workspace + API"],["credit_layer","LLM CREDIT LAYER","One usage balance"],["request_router","REQUEST ROUTER","Metered requests"],["local_model","LOCAL MODEL","Local Language Model"],["gpu_cluster","GPU CLUSTER","Dedicated GPU infrastructure"],["response","RESPONSE","Chat · Code · Build"]];
const stateLabels:Record<string,string>={model_connected:"MODEL CONNECTED",interface_ready:"INTERFACE READY",implemented:"BUILT",backend_not_connected:"ACCESS NOT LIVE",relay_ready:"API RELAY",in_development:"MODEL IN DEVELOPMENT",telemetry_not_connected:"METRICS PENDING",hardware_reporting:"LIVE METRICS",awaiting_model:"MODEL IN DEVELOPMENT"};
function ComputeMark(){return <svg viewBox="0 0 360 290" fill="none" aria-hidden="true"><defs><linearGradient id="rack-stroke" x1="80" y1="20" x2="290" y2="280" gradientUnits="userSpaceOnUse"><stop stopColor="#797c7d"/><stop offset="1" stopColor="#292b2c"/></linearGradient></defs><path d="M10 250 175 155 350 255M10 200l165-95 175 95M10 150l165-95 175 95" stroke="#202223"/><path d="m77 84 103-59 103 59v123l-103 59-103-59V84Z" fill="#111314" stroke="url(#rack-stroke)"/><path d="m77 84 103 59 103-59M180 143v123" stroke="#515456"/>{[0,1,2].map(i=><g key={i}><path d={"m91 "+(104+i*34)+" 75 43v17l-75-43v-17Z"} fill="#181a1c" stroke="#373a3c"/><path d={"m194 "+(148+i*34)+" 75-43v17l-75 43v-17Z"} fill="#151719" stroke="#373a3c"/><path d={"M104 "+(119+i*34)+"l17 10"} stroke="#a0a29e"/><circle cx="153" cy={146+i*34} r="2" fill="#878986"/></g>)}<path d="m180 25 27 16-104 60-26-17 103-59Z" fill="#202325" opacity=".7"/><path d="M38 267h55m174 0h55M180 285v-12" stroke="#626564"/><circle cx="38" cy="267" r="3" stroke="#626564"/><circle cx="322" cy="267" r="3" stroke="#626564"/></svg>;}
export function ComputeHome({me,status,accountState,connect}:Props){
 const [network,setNetwork]=useState<Network|null>(null),[networkError,setNetworkError]=useState(false),[now,setNow]=useState(Date.now());
 const readings=accountReadings(me);
 useEffect(()=>{if(!("IntersectionObserver" in window)||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add("compute-entered");observer.unobserve(entry.target);}},{threshold:0.08});document.querySelectorAll(".compute-page > section").forEach(node=>observer.observe(node));return()=>observer.disconnect();},[]);
 useEffect(()=>{let live=true;const controller=new AbortController();async function refresh(){try{const r=await fetch("/api/network",{signal:controller.signal,cache:"no-store"});if(!r.ok)throw new Error("Telemetry unavailable");const value=await r.json();if(!value?.metrics||!Array.isArray(value.architecture))throw new Error("Invalid network state");if(live){setNetwork(value);setNetworkError(false);}}catch{if(live){setNetwork(null);setNetworkError(true);}}}void refresh();const timer=setInterval(()=>{if(document.visibilityState!=="hidden")void refresh();},15000);return()=>{live=false;controller.abort();clearInterval(timer);};},[]);
 useEffect(()=>{if(!readings.reset)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[readings.reset]);
 const reset=readings.reset?new Date(readings.reset).toISOString():null;
 const remaining=readings.reset?Math.max(0,Math.floor((readings.reset-now)/1000)):null;
 const countdown=remaining===null?"—":remaining===0?"Claim closed":[Math.floor(remaining/3600),Math.floor(remaining/60)%60,remaining%60].map(x=>String(x).padStart(2,"0")).join(":");
 const connected=!!me,available=!!status?.customModel?.available,liveTelemetry=network?.telemetryStatus==="reporting";
 const modelLabel=available?"LOCAL LLM":"MODEL IN DEVELOPMENT";
 const metrics=network?.metrics;
 const telemetry=[["GPUs ONLINE",metrics?.gpusOnline===null||metrics?.gpusOnline===undefined?"—":String(metrics.gpusOnline)],["AGGREGATE VRAM",vram(metrics?.aggregateVramBytes)],["REQUESTS SERVED",count(metrics?.requestsServed)],["TOKENS GENERATED",count(metrics?.tokensGenerated)],["UTILIZATION",metrics?.utilizationBps===null||metrics?.utilizationBps===undefined?"—":(metrics.utilizationBps/100).toFixed(2)+"%"],["MODEL VERSION",metrics?.modelVersion??"—"]];
 return <div className="compute-page">
  <nav className="compute-nav" aria-label="Main navigation"><a className="compute-brand" href="/"><span className="compute-logo"><BrandSymbol/></span><span>LOCAL LANGUAGE<br/>MODEL</span></a><div className="compute-nav-links"><a href="#your-compute">ACCOUNT</a><a href="#local-workspace">WORKSPACE</a><a href="#llm-network">NETWORK</a><a href="/docs">DOCS</a><a href="/pricing">PRICING</a></div><div className="compute-nav-actions"><SocialControls mint={status?.tokenMint}/><button className={"compute-connect "+(connected?"connected":"")} onClick={connect}>{connected?<><i/>{me.wallet.slice(0,4)+"…"+me.wallet.slice(-4)}</>:"CONNECT WALLET"}<span aria-hidden="true">↗</span></button></div></nav>
  <section className="compute-hero" aria-labelledby="compute-title"><div className="compute-hero-copy"><span className="compute-eyebrow">LOCAL LANGUAGE MODEL / $LLM</span><h1 id="compute-title" aria-label="HOLD $LLM. USE AI."><span className="compute-title-line">HOLD <span className="compute-token-type">$LLM<span className="compute-type-corner" aria-hidden="true"/></span>.</span><br/><span className="compute-title-line">USE AI.</span></h1><p>Hold $LLM to receive daily compute credits for Local Language Model.<br/><span>Chat. Code. Build. Run inference.</span></p><div className="compute-actions"><button className="compute-button" onClick={connect}>{connected?"VIEW WALLET":"CONNECT WALLET"}<span aria-hidden="true">↗</span></button><a className="compute-button outline" href="#your-compute">EXPLORE COMPUTE<span aria-hidden="true">↓</span></a></div><div className="compute-status-line"><span>{available?"MODEL CONNECTED":"NETWORK PREVIEW"}</span><b>•</b><span>DEDICATED COMPUTE</span><b>•</b><span>SOLANA</span></div></div><div className="compute-atmosphere"><span className="compute-panel-index" aria-hidden="true">LLM / COMPUTE ARRAY</span><ComputeMark/><span className="compute-panel-scan" aria-hidden="true"/><div><span>ACCOUNT → MODEL → NETWORK</span><small>ARCHITECTURE PREVIEW</small></div></div></section>
  <section className="compute-account" id="your-compute" aria-labelledby="compute-account-title"><div className="compute-section-top"><h2 id="compute-account-title">YOUR COMPUTE</h2><span className={connected?"compute-state connected":"compute-state"}><i/>{connected?"WALLET CONNECTED":accountState==="loading"?"CHECKING ACCOUNT":"WALLET NOT CONNECTED"}</span></div><dl className="compute-readings"><div><dt>$LLM HELD</dt><dd>{accountState==="loading"&&!me?"—":readings.held}</dd></div><div><dt>DAILY CREDITS</dt><dd>{readings.daily}</dd></div><div><dt>REMAINING</dt><dd className={me?.balance>0?"credits-available":""}>{readings.remaining}</dd></div><div><dt>RESET</dt><dd><time dateTime={reset??undefined} title={reset??"No active daily allocation"}>{countdown}</time></dd></div></dl><div className="compute-account-bottom"><p>{me?me.holder?.reason??"Your holding history determines eligibility.":"Connect wallet to calculate your allowance."}{reset&&<small>Published claim deadline: {new Date(readings.reset!).toLocaleString("en-US",{timeZone:"UTC"})} UTC.</small>}{me?.holder?.observedAt&&<small>Token balance observed: {new Date(me.holder.observedAt).toLocaleString()}.</small>}</p>{me?<a href="/credits">{me.holder?.claimAvailable?"CLAIM DAILY CREDITS":"VIEW ALLOWANCE"} ↗</a>:<button onClick={connect}>CONNECT WALLET ↗</button>}</div><div className="compute-account-note">{accountState==="unavailable"?"Account access is not live yet.":status?.paused?"Daily claims are currently paused.":"Eligible holders share the funded daily pool."} Daily credits expire 24 hours after issuance.</div></section>
  <section className="compute-utility" aria-labelledby="utility-title"><div className="compute-heading"><span className="compute-eyebrow">01 / COMPUTE ACCOUNT</span><h2 id="utility-title">YOUR TOKENS.<br/>YOUR COMPUTE.</h2><p>A token balance becomes a usage balance. Eligible holders claim a proportional share of a funded daily pool.</p></div><ol className="compute-pipeline" aria-label="Holder compute flow">{["HOLD $LLM","RECEIVE DAILY CREDITS","RUN LOCAL LLM","CREDITS CONSUMED"].map((label,i)=><li key={label}><small>{String(i+1).padStart(2,"0")}</small><span>{label}</span>{i<3&&<b aria-hidden="true">→</b>}</li>)}</ol><div className="compute-more"><strong>NEED MORE?</strong><span aria-hidden="true">→</span><a href="/credits">BUY CREDITS <b>/</b> BURN $LLM</a><span aria-hidden="true">→</span><strong>MORE COMPUTE</strong></div><p className="compute-fine">Holding supports recurring funded allocations. Buying or verified burning adds immediate usage when available. Burns are irreversible and require a funded reserve.</p></section>
  <section className="compute-network-section" id="llm-network" aria-labelledby="network-title"><div className="compute-heading"><span className="compute-eyebrow">02 / GPU NETWORK</span><h2 id="network-title">THE LLM NETWORK.</h2><p>From your wallet to the model. One credit layer connects the workspace, developer API and compute network.</p></div><div className="compute-network-panel"><div className="compute-section-top"><span>REQUEST ARCHITECTURE</span><span className={"compute-state "+(network?.inferenceConnected?"connected":"")}><i/>{network?.inferenceConnected?"MODEL CONNECTED":"NETWORK PREVIEW"}</span></div><ol className={"compute-route "+(network?.inferenceConnected?"compute-route-connected":"")} aria-label="Network request path">{stages.map(([id,label,detail],i)=>{const node=network?.architecture.find(n=>n.id===id);return <li key={id}><small>{String(i+1).padStart(2,"0")}</small><strong>{node?.label??label}</strong><span>{node?.detail??detail}</span><em>{node?.state?stateLabels[node.state]??node.state.replaceAll("_"," ").toUpperCase():id==="local_model"?"MODEL IN DEVELOPMENT":"PREVIEW"}</em>{i<stages.length-1&&<b aria-hidden="true">→</b>}</li>;})}</ol><div className="compute-telemetry-top"><h3>NETWORK TELEMETRY</h3><span>{liveTelemetry?"LIVE METRICS":networkError?"METRICS UNAVAILABLE":"AWAITING LIVE METRICS"}</span></div><dl className="compute-telemetry">{telemetry.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="compute-network-bottom"><span className={"compute-state "+(liveTelemetry?"connected":"")}><i/>{liveTelemetry?"GPU METRICS · MODEL "+(network?.inferenceConnected?"CONNECTED":"IN DEVELOPMENT"):"NETWORK PREVIEW"}</span><span>{network?.observedAt?"SAMPLED "+new Date(network.observedAt).toLocaleString():"Live readings appear when telemetry is connected."}</span></div><p className="compute-fine">{liveTelemetry?"Live GPU readings from our compute infrastructure.":"Live GPU readings will appear as telemetry comes online."} Your account. Our compute.</p></div></section>
  <section className="compute-workspace-section" id="local-workspace" aria-labelledby="workspace-title"><div className="compute-heading"><span className="compute-eyebrow">03 / LOCAL MODEL WORKSPACE</span><h2 id="workspace-title">ONE BALANCE.<br/>EVERY REQUEST.</h2><p>Chat, code and build in the workspace. Connect your tools through the API. Every request uses the same metered credit balance.</p></div><div className="compute-workspace-preview"><div className="compute-workspace-header"><div><span className="compute-mini-logo"><BrandSymbol/></span><strong>LOCAL LLM</strong><span className="compute-model-version">LLM-1 // PREVIEW</span></div><span className={available?"compute-state connected":"compute-state"}><i/>{modelLabel}</span></div><nav className="compute-workspace-tabs" aria-label="Workspace tools"><a href="/chat">CHAT</a><a href="/chat?mode=code">CODE</a><a href="/context">BUILD</a><a href="/developers">API</a></nav><div className="compute-workspace-body"><span className="compute-eyebrow">YOUR NEXT REQUEST</span><h3>Put your compute<br/>to work.</h3><p>{available?"Open your workspace to run the connected model.":"Prepare your next request. Bring your context. Build from one workspace."}</p><a className="compute-button" href="/chat">OPEN WORKSPACE<span aria-hidden="true">↗</span></a></div><div className="compute-workspace-footer"><span>LOCAL LANGUAGE MODEL</span><span>{me?readings.remaining+" AVAILABLE":"CONNECT WALLET FOR YOUR BALANCE"}</span></div></div></section>
  <section className="compute-built" aria-labelledby="built-title"><div><span className="compute-eyebrow">DEDICATED GPU INFRASTRUCTURE</span><h2 id="built-title">BUILT ON<br/>OUR COMPUTE.</h2></div><div><p>Four NVIDIA RTX 5090 GPUs. A Threadripper PRO platform. Dedicated hardware built for Local Language Model.</p><dl className="compute-inventory"><div><dt>GPU ARRAY</dt><dd>4× RTX 5090 / 32GB each</dd></div><div><dt>AGGREGATE VRAM</dt><dd>128GB across four separate devices</dd></div><div><dt>SYSTEM</dt><dd>Threadripper PRO / 256GB ECC</dd></div></dl><p className="compute-fine">128GB of GPU memory across four 32GB devices. 256GB of ECC system memory. One dedicated compute stack.</p><a href="/docs#setup">VIEW INFRASTRUCTURE DETAILS ↗</a></div></section>
  <section className="compute-scale" aria-labelledby="scale-title"><span className="compute-eyebrow">MEASURE. FUND. EXPAND.</span><h2 id="scale-title">SCALE THE NETWORK.<br/>SCALE THE MODEL.</h2><p>More capacity for more builders. We expand the network around measured workloads, clear pricing and funded daily credits.</p><a href="/transparency">INSPECT FUNDING &amp; CAPACITY ↗</a></section>
  <section className="compute-manifesto" id="manifesto" aria-labelledby="manifesto-title"><div className="compute-manifesto-label"><span className="compute-eyebrow">THE LOCAL LANGUAGE MODEL MANIFESTO</span><span aria-hidden="true">[ 01 — 03 ]</span></div><h2 id="manifesto-title">INTELLIGENCE<br/>SHOULD BE <span>OPEN.</span></h2><p className="compute-manifesto-intro">AI is becoming an everyday expense. Access to it should not belong to a handful of companies. This is what we’re building toward.</p><ol className="compute-principles"><li><span aria-hidden="true">01 /</span><div><h3>DECENTRALIZE THE COMPUTE.</h3><p>More independent infrastructure. More choice over where intelligence runs. A network that grows beyond a single gatekeeper.</p></div></li><li><span aria-hidden="true">02 /</span><div><h3>KEEP IDEAS FREE.</h3><p>AI should make room for difficult questions, independent thinking and open inquiry. People should be able to explore ideas without arbitrary censorship.</p></div></li><li><span aria-hidden="true">03 /</span><div><h3>MAKE ACCESS AFFORDABLE.</h3><p>Clear prices. Useful credits. Measured consumption. Hold $LLM, claim funded daily credits and put them to work.</p></div></li></ol><div className="compute-manifesto-signoff"><BrandSymbol/><span>MORE PEOPLE BUILDING.<br/>MORE PEOPLE IN CONTROL.</span><a href="/chat">PUT YOUR IDEAS TO WORK ↗</a></div></section>
  <section className="compute-final" aria-labelledby="final-title"><span className="compute-eyebrow">LOCAL LANGUAGE MODEL / $LLM</span><h2 id="final-title">COMPUTE SHOULD COME<br/>WITH THE TOKEN.</h2><p>Hold $LLM. Get credits. Run Local Language Model.</p><button className="compute-button" onClick={connect}>{connected?"VIEW WALLET":"CONNECT WALLET"}<span aria-hidden="true">↗</span></button><small>Eligibility, available funding and model availability determine access.</small></section>
  <footer className="compute-footer"><span>LOCAL LANGUAGE MODEL <b>$LLM</b></span><div><a href="/docs">DOCS</a><a href="/pricing">PRICING</a><a href="/transparency">TRANSPARENCY</a><a href="/developers">API</a></div><span>NETWORK PREVIEW</span></footer>
 </div>;
}
