import {useEffect,useState,type ReactNode} from "react";
import {BrandSymbol} from "./social";
import {Architecture,Callout,DocCode,ExactTokens,ParameterTable,StatusBadge,TransactionLink,type DocState} from "./docs-components";
import {money} from "../server/money";
import "./docs.css";
export const DOC_ROUTES=[{path:"/docs",title:"Overview"},{path:"/docs/llm",title:"$LLM token"},{path:"/docs/credits",title:"Compute credits"},{path:"/docs/model",title:"LocalLM model"},{path:"/docs/network",title:"Compute network"},{path:"/docs/buyback-burn",title:"Buyback + Burn"},{path:"/docs/api",title:"Developer API"},{path:"/docs/security",title:"Security + privacy"},{path:"/docs/roadmap",title:"Roadmap"},{path:"/docs/benchmarks",title:"Benchmarks"}] as const;
type Section={id:string,title:string,content:ReactNode};
type Page={title:string,summary:string,state:DocState,sections:Section[]};
const moneyOrDash=(value:unknown)=>typeof value==="number"&&Number.isSafeInteger(value)&&value>=0?money(value):"—";
const holdingFlow=[{label:"HOLD $LLM"},{label:"DAILY COMPUTE CREDITS"},{label:"LOCAL MODEL"},{label:"GPU INFERENCE",state:"BUILDING" as const}];
const systemFlow=[{label:"USER"},{label:"WALLET / CREDIT ACCOUNT"},{label:"REQUEST ROUTER"},{label:"LOCAL MODEL"},{label:"GPU COMPUTE",state:"BUILDING" as const},{label:"STREAMED RESPONSE"}];
const limits=[["Input","24 KB of text; 48 KB total request body. A conservative context check also applies."],["Output","Up to the verified model’s published output limit; never more than 4,096 tokens."],["Concurrency","Two pending requests per account; eight for the service."],["Frequency","Twelve requests per account per minute."],["Tools","Text-only API. Tool calls, images, attachments and embeddings are unsupported."]];
function BuybackReceipts(){const [data,setData]=useState<any>(null),[error,setError]=useState(false);useEffect(()=>{const controller=new AbortController();fetch("/api/buybacks",{signal:controller.signal,cache:"no-store"}).then(async r=>{if(!r.ok)throw Error("Unavailable");const value=await r.json();if(!Array.isArray(value.transactions))throw Error("Invalid receipt list");setData(value);}).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();},[]);const receipts=(data?.transactions??[]).filter((r:any)=>r.verified===true&&r.network==="solana-mainnet"&&typeof r.signature==="string"&&/^[1-9A-HJ-NP-Za-km-z]{80,90}$/.test(r.signature)&&typeof r.atomicAmount==="string"&&/^\d{1,40}$/.test(r.atomicAmount)&&typeof data?.mint==="string"&&r.mint===data.mint&&Number.isInteger(r.decimals)&&r.decimals===data.decimals&&r.decimals>=0&&r.decimals<=18);
return <div className="docs-burn-records"><div className="docs-burn-total"><span>CUMULATIVE VERIFIED BURN</span><strong><ExactTokens atomic={data?.cumulativeBurnAtomic} decimals={data?.decimals}/></strong><small>{data?.observedAt?"Observed "+new Date(data.observedAt).toLocaleString():"No verified cumulative total published."}</small></div><ParameterTable label="Verified buyback and burn receipts" columns={["Transaction","Amount burned","Network"]} rows={receipts.map((r:any)=>[<TransactionLink signature={r.signature}/>,<ExactTokens atomic={r.atomicAmount} decimals={r.decimals}/>,r.network])}/>{receipts.length===0&&<p className="docs-empty">{error?"Receipt feed is unavailable. No burn totals are inferred.":"No verified buyback or burn transactions have been published."}</p>}</div>;}
function contentPages(status:any):Record<string,Page>{const model=status?.model,serving=!!model?.available,backend=!!status?.backendConfigured,daily=backend&&!status?.paused&&status?.dailyBudget>0,purchase=serving&&!!status?.purchaseConfigured&&!status?.purchaseStock?.exhausted;const live=(value:boolean):DocState=>value?"LIVE":"BUILDING",base=window.location.origin+"/api/v1",output=Math.min(1024,model?.maxOutput??1024);const curl='export OUR_API_BASE_URL="'+base+'"\nexport OUR_USER_API_KEY="YOUR_SERVICE_API_KEY"\n\ncurl -N "$OUR_API_BASE_URL/chat/completions" \\\n  -H "Authorization: Bearer $OUR_USER_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"model":"local-language-model","stream":true,"max_tokens":'+output+',"messages":[{"role":"user","content":"Hello"}]}\'';
const javascript='const OUR_API_BASE_URL = "'+base+'";\nconst OUR_USER_API_KEY = process.env.OUR_USER_API_KEY;\n\nconst response = await fetch(OUR_API_BASE_URL + "/chat/completions", {\n  method: "POST",\n  headers: {\n    Authorization: "Bearer " + OUR_USER_API_KEY,\n    "Content-Type": "application/json"\n  },\n  body: JSON.stringify({\n    model: "local-language-model", stream: true, max_tokens: '+output+',\n    messages: [{ role: "user", content: "Hello" }]\n  })\n});\nif (!response.ok) throw new Error(await response.text());\nfor await (const chunk of response.body) process.stdout.write(Buffer.from(chunk));';
return {
"/docs":{title:"Local LLM, explained.",summary:"A compute account for AI. Your wallet, credits, workspace and API connect through one application.",state:live(serving),sections:[
{id:"what-is-local-llm",title:"Start here",content:<><p>Local Language Model is an AI workspace and a metered compute service. $LLM is the project token. Eligible holders can claim a share of a funded daily credit pool; users can also purchase compute directly.</p><p>Credits pay for requests in chat and through the developer API. LocalLM is the assistant identity. The brand name does not mean a request runs on your phone or laptop.</p><Architecture label="Core system · dedicated GPU serving is building" steps={holdingFlow}/></>},
{id:"architecture",title:"One request, end to end",content:<><Architecture label="Local LLM target architecture" steps={systemFlow}/><p>The account layer authenticates a wallet or service key. It reserves the maximum permitted charge before routing the request, streams the answer, then settles complete usage and releases unused credit.</p><Callout title="Current serving connection" state={live(serving)}><p>{serving?"LocalLM has a verified serving connection. The workspace and API share the same rates and balance.":"The workspace is in network preview. Paid inference opens after the serving connection and funded capacity are verified."} Dedicated GPU execution is a separate connection step; hardware inventory alone does not identify where a request ran.</p></Callout></>},
{id:"use-compute",title:"Get compute",content:<><ParameterTable label="Ways to access compute" columns={["Path","How it works","State"]} rows={[["Hold $LLM","Qualify for 24 hours, then claim the frozen funded allocation.",<StatusBadge state={live(daily)}/>],["Buy credits","Purchase the $1 launch package with canonical Solana USDC.",<StatusBadge state={live(purchase)}/>],["Burn $LLM","Where enabled, redeem a verified token burn for quoted compute.",<StatusBadge state={live(serving&&!!status?.burnConfigured)}/>]]}/><p>Open <a href="/credits">Credits</a> to see eligibility, quote availability and your balance. $5, $10 and $20 packages are planned.</p></>},
{id:"revenue",title:"Revenue and token supply",content:<><p>Paid network usage can generate revenue. The intended loop is paid compute → revenue → $LLM buyback → $LLM burn. The buyback program is <StatusBadge state="PLANNED"/> and has no published allocation percentage, schedule or automated execution.</p><p><a href="/docs/buyback-burn">Buyback + Burn</a> separates that proposed treasury activity from a user’s burn-for-compute redemption.</p></>},
{id:"setup",title:"Keep reading",content:<><p>Explore <a href="/docs/credits">credit accounting</a>, <a href="/docs/network">the compute network</a> and <a href="/docs/api">API integration</a>. Live availability and prices come from the service, rather than fixed promises in these documents.</p><p>The owner’s configuration guide is at <a href="/setup">Service setup</a>.</p></>}
]},
"/docs/llm":{title:"$LLM token",summary:"The canonical Solana token connects a qualifying holding balance to funded daily compute allocations.",state:live(daily),sections:[
{id:"utility",title:"Hold. Qualify. Claim.",content:<><Architecture label="Holder utility" steps={holdingFlow}/><p>Eligibility requires a full 24-hour qualifying holding period. The canonical mint, decimals and minimum balance are configuration values. The current mint appears in the site’s CA control when configured; an empty CA is not a mint.</p><p>A qualifying balance determines a proportional allocation weight. No fixed credit value per token is promised.</p></>},
{id:"eligibility",title:"Evidence and transfers",content:<><p>Finalized chain history must prove the qualifying balance. If that history is unavailable, the holding period accumulates from a verified baseline. Receiving transferred tokens restarts the required holding period.</p><p>Each epoch freezes the eligible holder set before claims. Transferring the same balance cannot generate a second allocation inside that frozen epoch. Splitting an eligible balance across wallets does not increase total proportional rewards.</p><p>Treasury, liquidity, burn and other configured excluded addresses do not qualify. The account view explains an address’s qualification status.</p></>},
{id:"funding",title:"Funded allocations",content:<><Callout title="100% of creator fees for infrastructure"><p>100% of creator fees received will be used for infrastructure, hardware and scaling the network. This allocation commitment is separate from the planned buyback policy. Cleared receipts and verified spending will appear on the <a href="/transparency">transparency page</a>.</p></Callout><p>Daily pools use cleared operator funding and available operating surplus. Projected fees, market capitalization and unsold treasury tokens are not spendable compute funding.</p><p>Existing credit obligations, overlapping epochs, quote reservations and the operating buffer are covered before a new pool opens. Future budget changes do not rewrite a frozen allocation.</p><Callout title="Usage utility"><p>Credits are access to this service. Holding $LLM does not promise daily cash returns, unlimited inference or a share of project revenue.</p></Callout></>}
]},
"/docs/credits":{title:"Compute credits",summary:"One usage balance for chat and API, with separate auditable lots and exact integer accounting.",state:live(backend),sections:[
{id:"credit-lots",title:"What expires",content:<ParameterTable label="Credit expiration policy" columns={["Credit lot","Issued by","Expiration"]} rows={[["Daily promotional","One claim per eligible wallet per frozen epoch","24 hours after issuance; no rollover."],["Purchased","Finalized verified USDC payment","No daily expiration."],["Burn-redeemed","Finalized canonical burn with a valid quote","No daily expiration."],["Unclaimed allocation","Frozen daily epoch","Published claim deadline."]]}/>},
{id:"daily",title:"Daily claims",content:<><StatusBadge state="BUILDING"/><p>Daily claims are coming soon and the claim button is disabled. Existing issued credits keep their disclosed expiration.</p><p>The Credits page shows the verified eligible balance, qualification reason, allocation, claim availability and exact deadline. Claims add credits directly to the account. No code needs to be copied into chat.</p><p>The pool is proportional and fixed before claims begin. If a wallet has no proven eligibility, no allocation or an already-claimed allocation, it cannot claim again.</p><p>Claimed credits remain backed until their disclosed expiration, including when an adjacent epoch is open.</p></>},
{id:"purchase",title:"Buy credits",content:<><StatusBadge state={live(purchase)}/><p>The launch package is $1 in canonical Solana USDC for $1 of service usage. $5, $10 and $20 are disabled until released. Network transaction fees are shown separately.</p><ol><li>Connect a wallet and select the $1 package on <a href="/credits">Credits</a>.</li><li>Request a quote. Review amount, recipient, mint, credits, fee and expiration.</li><li>Sign the exact quoted transaction.</li><li>Verify the finalized receipt. Credit appears directly in the account.</li></ol><p>The server checks the network, canonical USDC mint, amount, recipient, order reference, successful finalization and transaction uniqueness. A browser success callback cannot create credits.</p><p>When a launch inventory limit is configured, pending orders occupy a slot. An unresolved signed transaction keeps both its slot and funding reservation until reconciliation.</p></>},
{id:"burn-compute",title:"Burn $LLM for compute",content:<><StatusBadge state={live(serving&&!!status?.burnConfigured)}/><p>Where enabled, request an explicit quote before burning. The quote discloses tokens, credits, fee, expiration and irreversibility. The service reserves funded capacity before allowing the transaction.</p><p>Redemption uses a configured, capped fixed promotional conversion. No thin-pool trade sets the price. Only the canonical mint and an actual finalized burn instruction are accepted; a transfer to a wallet is not a burn.</p><p>Holding supports recurring funded allocations. Burning gives additional immediate usage. This user redemption is separate from the <a href="/docs/buyback-burn">planned revenue buyback program</a>.</p></>},
{id:"accounting",title:"Reservation and settlement",content:<><p>One dollar equals 1,000,000,000 integer accounting units. One dollar of credit buys one dollar of usage at the published service rates. Credits are not cash, transferable tokens or another provider’s account credits.</p><p>The ledger spends the earliest-expiring available lots first. Requests atomically reserve a conservative maximum, settle complete input/output usage once and release the unused unexpired amount.</p><p>Daily grants, purchases, redemptions, reservations, settlements, releases and expirations each create ledger entries. A disconnect or retry does not prove zero inference cost.</p></>}
]},
"/docs/model":{title:"LocalLM model",summary:"LocalLM is the assistant for Local Language Model. Availability, context and serving rates are verified before use.",state:live(serving),sections:[
{id:"identity",title:"Assistant identity",content:<><p>LocalLM connects the project workspace, credit layer and serving adapter. It can help with text chat, coding and developer requests through the supported text interface.</p><p>The serving adapter is independent of accounts, balances and conversations. A future dedicated model can connect through its own verified endpoint without replacing the credit system.</p><Callout title="Execution"><p>{serving?"The serving connection is verified and available.":"Inference is building; the workspace remains available to explore."} The project’s GPU inventory is documented separately from live request execution.</p></Callout></>},
{id:"catalog",title:"Published model parameters",content:<ParameterTable label="Current verified model parameters" columns={["Parameter","Value"]} rows={[["Assistant","LocalLM"],["Availability",serving?"Available":"Awaiting verified serving connection"],["Context",serving&&model?.context?model.context.toLocaleString()+" tokens":"—"],["Maximum output",serving&&model?.maxOutput?model.maxOutput.toLocaleString()+" tokens":"—"],["Input / 1M tokens",moneyOrDash(model?.inputPerMillion)],["Output / 1M tokens",moneyOrDash(model?.outputPerMillion)],["Tools","Unsupported; no tool charges."],["Dedicated GPU execution",<StatusBadge state="BUILDING"/>]]}/>},
{id:"usage",title:"Usage behavior",content:<><p>The initial interface supports text messages and streaming responses. Markdown, code highlighting, copying, conversation history and stopping are workspace features.</p><p>Retries create new billable requests. Partial or uncertain execution keeps the original reservation until verified usage can reconcile it. Model identity and complete usage must match the serving configuration before settlement.</p></>},
{id:"evaluation",title:"Evaluation before claims",content:<><p>Model quality, latency, throughput, quantization and cost depend on the actual model and deployment. No benchmark numbers are inferred from hardware specifications.</p><p><a href="/docs/benchmarks">Benchmarks</a> will publish reproducible results with model version, hardware, workload, source prices and measurement dates.</p></>}
]},
"/docs/network":{title:"Compute network",summary:"The application separates accounts, routing, model execution and GPU telemetry.",state:"BUILDING",sections:[
{id:"architecture",title:"Request architecture",content:<><Architecture label="Local LLM target architecture" steps={systemFlow}/><p>Wallet and API authentication resolve to one account. The credit layer owns reservations and settlements. The router calls the configured serving adapter. Tokens stream back to the client while settlement remains on the server.</p><p>Dedicated GPU execution is building. The current verified adapter can serve requests independently while that route is connected.</p></>},
{id:"hardware",title:"Project hardware inventory",content:<><ParameterTable label="Project supplied compute inventory" columns={["Component","Inventory"]} rows={[["GPU array","4 × NVIDIA RTX 5090; 32GB per GPU."],["Aggregate device memory","128GB across four separate GPUs."],["Processor","Threadripper PRO platform."],["System memory","256GB ECC."]]}/><p>This is project inventory. It is not a live GPU count, pooled single-device memory figure, benchmark or inference throughput measurement.</p></>},
{id:"telemetry",title:"Live telemetry",content:<><p>The homepage reads GPUs online, aggregate VRAM, requests served, tokens generated, utilization, model version and observation time from the authenticated telemetry source.</p><p>Disconnected, stale or invalid readings remain unknown. A hardware reading does not activate an unverified model or prove that a particular request ran on that machine.</p><Callout title="Network state" state="BUILDING"><p>Use the <a href="/#llm-network">network panel</a> for the current readings. Missing measurements appear as an em dash.</p></Callout></>},
{id:"capacity",title:"Financial and technical capacity",content:<><p>Financial capacity includes cleared serving funds, issued-credit obligations, frozen daily pools, valid quote reservations and the operating buffer. Technical capacity includes output limits, context limits, throughput and concurrency.</p><p>Private serving balances are verified before new grants, quotes or requests. If funding evidence is unavailable or insufficient, new issuance stops. Previously issued obligations remain recorded.</p><p>Separate budgets cover existing purchased/burned credits, holder subsidies and operating overhead. Burns create no operating cash.</p></>}
]},
"/docs/buyback-burn":{title:"Buyback + Burn",summary:"A planned revenue policy with a receipt structure for independently verifiable token transactions.",state:"PLANNED",sections:[
{id:"economic-loop",title:"Intended economic loop",content:<><Architecture label="Proposed revenue loop" steps={[{label:"PAID COMPUTE",state:live(purchase)},{label:"REVENUE"},{label:"$LLM BUYBACK",state:"PLANNED"},{label:"$LLM BURN",state:"PLANNED"}]}/><p>Paid compute generates service revenue as usage is earned. Purchased but unspent credits remain a service obligation. The intended policy is to use a disclosed share of available revenue for $LLM buybacks and verified burns.</p><Callout title="Policy is planned" state="PLANNED"><p>No buyback allocation percentage, execution schedule, venue or automatic trigger has been published. There are no projected burns presented as completed transactions.</p></Callout></>},
{id:"reserve-policy",title:"Protect existing compute",content:<><p>Buyback spending must come after provider costs, purchased-credit obligations, funded daily grants and the operating buffer. Token market capitalization and unreceived fees are not available revenue.</p><p>The planned policy does not create a redemption price, dividend, guaranteed token return or promise of price support.</p></>},
{id:"verified-transactions",title:"Verified transaction receipts",content:<><p>Future receipts will identify the canonical mint, successful finalized buyback and burn transactions, exact atomic burn amount, decimals and cumulative verified burn. Every transaction needs a chain explorer link.</p><BuybackReceipts/></>},
{id:"distinction",title:"Buybacks versus burn-for-compute",content:<ParameterTable label="Separate token burn mechanisms" columns={["Mechanism","Source","Result"]} rows={[["Revenue buyback + burn","Planned use of available earned revenue","Treasury buys tokens and verifies a supply-reducing burn."],["User burn redemption","User’s tokens and a backed service quote","User receives additional compute credit; no operating cash is generated."]]}/>}
]},
"/docs/api":{title:"Developer API",summary:"Scoped service keys, a shared account balance and a documented text-streaming endpoint.",state:live(serving),sections:[
{id:"keys",title:"Create a service key",content:<><p>Connect your wallet on <a href="/developers">Developers</a>. Create a named key, optionally set a total spending cap and copy the secret once. Store it in your application’s server-side secret manager.</p><p>Secrets are hashed in storage. Keys are scoped to text chat, share the wallet’s credit balance, track use separately and can be revoked. Revocation blocks new requests; work already executing still settles.</p></>},
{id:"endpoint",title:"Supported endpoint",content:<><DocCode title="Endpoint" code="POST /api/v1/chat/completions"/><ParameterTable label="Text chat parameters" columns={["Field","Type","Behavior"]} rows={[["model","string","local-language-model"],["messages","array","1–50 text messages; role is user, assistant or system; content is a string."],["stream","boolean","Required; true only."],["max_tokens","integer","Optional; defaults to 1,024. Use 1 up to the published model output limit."]]}/><p>This is a supported text-chat subset. Images, files, tools, embeddings and non-streaming responses are unsupported. Client system text is treated as client context beneath the application identity.</p></>},
{id:"curl",title:"curl",content:<DocCode title="curl example" code={curl}/>},
{id:"javascript",title:"JavaScript · Node.js",content:<DocCode title="JavaScript example" code={javascript}/>},
{id:"streaming",title:"Streaming and billing",content:<><p>Responses use server-sent events with chat completion chunks. Successful completion includes normalized prompt/completion tokens, a final stop chunk and [DONE]. The llm_billing object includes charge, reserved amount, nanodollar unit and request ID.</p><p>Save request IDs. An uncertain response identifies the request and keeps its reservation. Retrying sends new work and can create another charge.</p><ParameterTable label="Request error responses" columns={["Status","Meaning"]} rows={[["401","Invalid or revoked account key."],["402","Insufficient account credits or spending cap."],["413","Input exceeds the service or context limit."],["429","Frequency or concurrency limit reached."],["503","Serving, funding or account service unavailable."]]}/></>},
{id:"limits",title:"Request limits",content:<ParameterTable label="Service request limits" columns={["Limit","Behavior"]} rows={limits}/>}
]},
"/docs/security":{title:"Security + privacy",summary:"Signed wallet authentication, private serving credentials and an auditable account ledger.",state:live(backend),sections:[
{id:"wallet",title:"Wallet authentication",content:<><p>Sign a one-time nonce message to authenticate. The signature does not transfer tokens. Nonces expire and cannot be replayed; sessions expire after twelve hours.</p><p>Browser mutation requests check their origin. Session cookies are HttpOnly, SameSite=Strict and Secure on HTTPS. Never enter a seed phrase or wallet private key into this site.</p></>},
{id:"ledger",title:"Financial boundaries",content:<><p>The durable backend owns balances. Ledger rows reject updates and deletes. Atomic database transactions enforce one claim per epoch, unique receipts, request reservations, spending caps and single settlement.</p><p>The database is not directly exposed to the browser. Administration requires a private server credential. Privileged keys do not belong in the client bundle.</p><p>A restart releases undispatched work only. Dispatched work with uncertain usage remains reserved until reconciliation has sufficient evidence.</p></>},
{id:"payments",title:"Payment and burn verification",content:<><p>Transactions are checked against the exact quote message, canonical mint, signer, network, amount, recipient where applicable and finalized success. Receipt signatures and quote IDs are unique.</p><p>A transfer is not a burn. Issued quotes retain capacity through uncertain or late settlement; expiry alone cannot refund a burn that may have happened.</p></>},
{id:"privacy",title:"Data and private configuration",content:<><p>Accounts retain conversations, transaction history and usage records. Imported Context Studio text is prepared in your browser and is not uploaded until you choose to send it.</p><p>Server-side inference processes submitted messages. The private serving route requests no data collection and zero-retention endpoints. Conversations are not automatically added to a training dataset. Account history still exists; this is not a zero-records or zero-tracking claim.</p><p>Public funding and transaction receipts exclude prompts, credentials and service-key secrets. Private routing configuration stays server-side.</p></>},
{id:"limits",title:"Input and execution limits",content:<ParameterTable label="Security limits" columns={["Boundary","Limit"]} rows={limits}/>}
]},
"/docs/roadmap":{title:"Roadmap",summary:"Work is organized by implemented product behavior, features being connected and future policy.",state:"BUILDING",sections:[
{id:"implemented",title:"Implemented application",content:<><p>The workspace, context preparation, wallet authentication, scoped API keys, exact ledger, request reservations and finalized-receipt verification are implemented. Runtime labels depend on the active backend connection and verified capacity.</p><ParameterTable label="Current runtime availability" columns={["Capability","State"]} rows={[["Context Studio",<StatusBadge state="LIVE"/>],["Wallet / account service",<StatusBadge state={live(backend)}/>],["Streaming LocalLM",<StatusBadge state={live(serving)}/>],["$1 compute purchase",<StatusBadge state={live(purchase)}/>],["Funded daily holder pool",<StatusBadge state="BUILDING"/>],["Quoted burn redemption",<StatusBadge state={live(serving&&!!status?.burnConfigured)}/>]]}/></>},
{id:"building",title:"Building",content:<><StatusBadge state="BUILDING"/><p>Connect dedicated GPU execution, normalize model usage and connect authenticated live telemetry. Measure concurrency, latency and serving cost before increasing budgets.</p><p>Private serving uses the same account and credit layer while the dedicated GPU route is connected.</p></>},
{id:"planned",title:"Planned",content:<><StatusBadge state="PLANNED"/><ul><li>$5, $10 and $20 prepaid credit packages.</li><li>Published, reproducible model and cost comparisons.</li><li>A disclosed revenue buyback-and-burn policy with verified receipts.</li><li>Expansion toward independently operated compute infrastructure.</li></ul><p>There are no promised delivery dates or token returns attached to these items.</p></>}
]},
"/docs/benchmarks":{title:"Benchmarks",summary:"The route for verified price, quality and performance measurements.",state:"PLANNED",sections:[
{id:"results",title:"Published results",content:<><Callout title="No verified comparisons published" state="PLANNED"><p>No blanket “90% cheaper” claim is established here. Model quality and workload must be compared alongside price.</p></Callout><p>Future results will include reproducible scripts and source evidence. An editable price assumption is not a measured service result.</p></>},
{id:"method",title:"Required measurement record",content:<ParameterTable label="Benchmark publication requirements" columns={["Field","Evidence"]} rows={[["Model","Exact model version, licensed weights and serving configuration."],["Hardware","GPU type/count, per-device memory, runtime and quantization."],["Workload","Prompt/output lengths, dataset, tools, cache policy and concurrency."],["Quality","Task metric, evaluation set and comparison limitations."],["Performance","Latency, time to first token, throughput and error rate."],["Price","Dated source input/output/tool rates, retail versus provider costs."],["Reproduction","Command, script revision, raw result and observation date."]]}/>},
{id:"prices",title:"Current service pricing",content:<><p>The <a href="/pricing">Pricing</a> page reports the verified serving rates when available. Rate evidence and an equivalent workload are required before publishing a savings comparison.</p></>}
]}
};}
export function Docs({path,status}:{path:string,status:any}){const [open,setOpen]=useState(false),pages=contentPages(status),page=pages[path],index=DOC_ROUTES.findIndex(r=>r.path===path);useEffect(()=>{document.title=(page?.title??"Page not found")+" · Local Language Model Docs";const timer=setTimeout(()=>{let id="";try{id=decodeURIComponent(window.location.hash.slice(1));}catch{}if(id)document.getElementById(id)?.scrollIntoView();},0);return()=>clearTimeout(timer);},[path]);
const nav=<nav aria-label="Documentation navigation">{DOC_ROUTES.map(r=><a key={r.path} href={r.path} aria-current={path===r.path?"page":undefined}>{r.title}{["/docs/buyback-burn","/docs/benchmarks"].includes(r.path)&&<span>PLANNED</span>}</a>)}</nav>;
return <div className="docs-shell"><header className="docs-top"><a className="docs-brand" href="/"><span className="docs-symbol"><BrandSymbol/></span><span>LOCAL LANGUAGE MODEL<small>DOCS / $LLM</small></span></a><nav aria-label="Docs primary navigation"><a href="/chat">WORKSPACE ↗</a><a href="/credits">CREDITS</a><a href="/docs" aria-current="page">DOCS</a></nav><button className="docs-mobile-toggle" aria-label="Toggle documentation navigation" aria-expanded={open} aria-controls="docs-sidebar" onClick={()=>setOpen(!open)}>{open?"CLOSE":"DOCS"} <span aria-hidden="true">{open?"−":"+"}</span></button></header><div className="docs-layout"><aside id="docs-sidebar" className={"docs-sidebar "+(open?"docs-sidebar-open":"")}><span className="docs-nav-label">DOCUMENTATION</span>{nav}<div className="docs-side-footer"><a href="/transparency">Funding + transparency ↗</a><a href="/">Back to Local LLM ↗</a></div></aside><main className="docs-article">{page?<><header className="docs-article-heading"><div><span className="docs-kicker">LOCAL LLM / DOCUMENTATION</span><StatusBadge state={page.state}/></div><h1>{page.title}</h1><p>{page.summary}</p></header><details className="docs-inline-toc"><summary>On this page</summary><nav aria-label="Article contents">{page.sections.map(s=><a key={s.id} href={"#"+s.id}>{s.title}</a>)}</nav></details>{page.sections.map(s=><section className="docs-section" id={s.id} key={s.id}><h2><a href={"#"+s.id}>{s.title}<span aria-hidden="true"> #</span></a></h2>{s.content}</section>)}<footer className="docs-pagination">{index>0?<a href={DOC_ROUTES[index-1].path}><small>PREVIOUS</small>{DOC_ROUTES[index-1].title} ←</a>:<span/>}{index<DOC_ROUTES.length-1&&<a href={DOC_ROUTES[index+1].path}><small>NEXT</small>{DOC_ROUTES[index+1].title} →</a>}</footer></>:<><h1>Documentation page not found.</h1><a href="/docs">Read the overview →</a></>}</main>{page&&<aside className="docs-toc"><span className="docs-nav-label">ON THIS PAGE</span><nav aria-label="Table of contents">{page.sections.map(s=><a key={s.id} href={"#"+s.id}>{s.title}</a>)}</nav><small>State reflects current service configuration. PLANNED items are not active features.</small></aside>}</div><footer className="docs-bottom"><span>LOCAL LANGUAGE MODEL / $LLM</span><span>EXACT ACCOUNTING. VERIFIED STATE.</span></footer></div>;}
