import {useState,type ReactNode} from "react";
export type DocState="LIVE"|"BUILDING"|"PLANNED";
export function StatusBadge({state}:{state:DocState}){return <span className={"docs-status docs-status-"+state.toLowerCase()}><i aria-hidden="true"/>{state}</span>;}
export function Callout({title,children,state}:{title:string,children:ReactNode,state?:DocState}){return <aside className="docs-callout"><div><strong>{title}</strong>{state&&<StatusBadge state={state}/>}</div><div>{children}</div></aside>;}
export function DocCode({title,code}:{title:string,code:string}){const [feedback,setFeedback]=useState("");return <div className="docs-code"><header><span>{title}</span><button type="button" aria-label={"Copy "+title} onClick={()=>void navigator.clipboard.writeText(code).then(()=>setFeedback("Copied")).catch(()=>setFeedback("Select code to copy"))}>{feedback||"Copy"}</button><span className="docs-copy-state" role="status">{feedback}</span></header><pre tabIndex={0}><code>{code}</code></pre></div>;}
export function Architecture({label,steps}:{label:string,steps:{label:string,state?:DocState}[]}){return <figure className="docs-diagram"><figcaption>{label}</figcaption><ol aria-label={label}>{steps.map((step,i)=><li key={i}><small>{String(i+1).padStart(2,"0")}</small><strong>{step.label}</strong>{step.state&&<StatusBadge state={step.state}/>}<span className="docs-diagram-arrow" aria-hidden="true">{i<steps.length-1?"→":"↳"}</span></li>)}</ol></figure>;}
export function ParameterTable({columns,rows,label}:{columns:string[],rows:ReactNode[][],label:string}){return <div className="docs-table"><table aria-label={label}><thead><tr>{columns.map(name=><th scope="col" key={name}>{name}</th>)}</tr></thead><tbody>{rows.map((cells,i)=><tr key={i}>{cells.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>;}
export function TransactionLink({signature,network="solana-mainnet"}:{signature:string,network?:string}){return network==="solana-mainnet"&&/^[1-9A-HJ-NP-Za-km-z]{80,90}$/.test(signature)?<a className="docs-transaction" href={"https://solscan.io/tx/"+encodeURIComponent(signature)} target="_blank" rel="noreferrer">{signature.slice(0,8)}…{signature.slice(-8)} ↗</a>:<span>Receipt unavailable</span>;}
export function ExactTokens({atomic,decimals}:{atomic:unknown,decimals:unknown}){if(typeof atomic!=="string"||!/^\d{1,40}$/.test(atomic)||typeof decimals!=="number"||!Number.isInteger(decimals)||decimals<0||decimals>18)return <>—</>;const value=BigInt(atomic),base=10n**BigInt(decimals),whole=(value/base).toString().replace(/\B(?=(\d{3})+(?!\d))/g,","),fraction=decimals?(value%base).toString().padStart(decimals,"0").replace(/0+$/,""):"";return <>{whole}{fraction?"."+fraction:""}</>;}
