import {useState} from "react";
import {contractAddress} from "./social-config";
function origin(value:string){try{const u=new URL(value);return u.protocol==="https:"&&!u.username&&!u.password&&!u.search&&!u.hash&&u.pathname==="/"?u.origin:"";}catch{return "";}}
function Block({title,value}:{title:string,value:string}){const [state,setState]=useState("");return <section className="setup-copy"><header><h2>{title}</h2><button type="button" className="copy" onClick={()=>void navigator.clipboard.writeText(value).then(()=>setState("Copied")).catch(()=>setState("Select the block to copy"))}>{state||"Copy"}</button></header><textarea aria-label={title} readOnly value={value} onFocus={e=>e.currentTarget.select()}/></section>;}
export function Setup(){const [backend,setBackend]=useState(""),[recipient,setRecipient]=useState(""),[margin,setMargin]=useState("20"),[buffer,setBuffer]=useState("1");const backendOrigin=origin(backend),wallet=contractAddress(recipient),bps=/^\d{1,3}$/.test(margin)&&Number(margin)<=100?Number(margin)*100:null,validBuffer=/^\d{1,7}(\.\d{1,9})?$/.test(buffer);
const railway=["NODE_ENV=production","PUBLIC_URL="+window.location.origin,"DB_PATH=/data/llm.sqlite","LLM_MODEL_PROTOCOL=hosted-credit-sse","LLM_MARKUP_BPS="+(bps??""),"LLM_CONTEXT_TOKENS=32768","LLM_MAX_OUTPUT_TOKENS=4096","PAYMENT_RECIPIENT="+wallet,"PURCHASE_ORDER_LIMIT=5","HOSTED_API_BASE_URL=","HOSTED_API_KEY=","HOSTED_MODEL=","HOSTED_PROVIDER_TAG=","SOLANA_RPC_URL=","ADMIN_KEY=","LLM_ADMIN_BASE_URL="+backendOrigin].join("\n");
const vercel="LLM_BACKEND_URL="+backendOrigin+"\nVITE_X_URL=\nVITE_LLM_CA=";
const commands="cd /app\nnode scripts/activate-funded.mjs --buffer "+(validBuffer?buffer:"1");
return <div className="page guides"><header className="page-heading"><span className="eyebrow">SERVICE SETUP</span><h1>Connect. Stock. Open checkout.</h1><p>Copy configuration blocks into your host. All fields below stay in this browser; nothing is saved or sent.</p></header><div className="setup-grid"><label>Railway HTTPS origin<input aria-label="Railway HTTPS origin" value={backend} onChange={e=>setBackend(e.target.value)} placeholder="https://your-service.up.railway.app" type="url"/></label><label>USDC recipient wallet<input aria-label="USDC recipient wallet" value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Your public receiving address"/></label><label>Service margin (%)<input aria-label="Service margin (%)" value={margin} onChange={e=>setMargin(e.target.value)} inputMode="numeric"/></label><label>Safety buffer (USD)<input aria-label="Safety buffer (USD)" value={buffer} onChange={e=>setBuffer(e.target.value)} inputMode="decimal"/></label></div>{((backend&&!backendOrigin)||(recipient&&!wallet)||bps===null||!validBuffer)&&<p role="alert">Use an HTTPS origin, a valid public wallet, a whole-number margin from 0–100 and an exact USD buffer.</p>}<p className="setup-note">Create the Railway service from /release with one replica and a /data volume. Use Railway → Variables → Raw Editor for the first block. Fill the blank private API URL, API key, model identifier, archive RPC URL and random ADMIN_KEY directly in Railway. Create the recipient’s canonical Solana USDC account. Never paste private keys or provider secrets into this page.</p><Block title="Railway variables" value={railway}/><Block title="Vercel variables" value={vercel}/><p className="setup-note">Paste the Vercel block into project environment settings and redeploy. The public CA and X values can remain blank until you are ready.</p><Block title="Activation command" value={commands}/><p className="setup-note">Run the activation command in the Railway service shell after private configuration and paid serving credits are ready. It checks live prices and funding, imports verified stock once, performs a paid streaming check, then opens $1 checkout with the chosen buffer. Daily holder issuance remains at zero until separately configured. Supabase is not required for this deployment.</p><p className="setup-note">The API URL and model identifier come from your private supplier dashboard. Generated blocks intentionally leave those values empty. PURCHASE_ORDER_LIMIT=5 caps completed plus pending purchase orders at five. Increase the limit after restocking; existing purchases remain recorded. Customer purchases require finalized USDC receipts; credits are added directly to their account.</p></div>;}
