import {useState} from "react";
import {contractAddress} from "./social-config";
function origin(value:string){try{const u=new URL(value.trim());return u.protocol==="https:"&&!u.username&&!u.password&&!u.search&&!u.hash&&u.pathname==="/"?u.origin:"";}catch{return "";}}
function routerBase(value:string){try{const u=new URL(value.trim());return u.protocol==="https:"&&!u.username&&!u.password&&!u.search&&!u.hash&&/^\/v1\/?$/.test(u.pathname)?u.origin+"/v1":"";}catch{return "";}}
function Block({title,value}:{title:string,value:string}){const [state,setState]=useState("");return <section className="setup-copy"><header><h2>{title}</h2><button type="button" className="copy" onClick={()=>void navigator.clipboard.writeText(value).then(()=>setState("Copied")).catch(()=>setState("Select the block to copy"))}>{state||"Copy"}</button></header><textarea aria-label={title} readOnly value={value} onFocus={e=>e.currentTarget.select()}/></section>;}
export function Setup(){
 const [backend,setBackend]=useState(""),[recipient,setRecipient]=useState(""),[route,setRoute]=useState("freellmapi"),[router,setRouter]=useState(""),[inputPrice,setInputPrice]=useState(""),[outputPrice,setOutputPrice]=useState(""),[buffer,setBuffer]=useState("1");
 const backendOrigin=origin(backend),wallet=contractAddress(recipient),base=routerBase(router),validBuffer=/^\d{1,7}(\.\d{1,9})?$/.test(buffer);
 const common=["NODE_ENV=production","PUBLIC_URL="+window.location.origin,"DB_PATH=/data/llm.sqlite","PAYMENT_RECIPIENT="+wallet,"PURCHASE_ORDER_LIMIT=5","SOLANA_RPC_URL=","ADMIN_KEY=","LLM_ADMIN_BASE_URL="+backendOrigin];
 const serving=route==="freellmapi"?["LLM_MODEL_PROTOCOL=freellmapi-sse","FREELLMAPI_BASE_URL="+base,"FREELLMAPI_API_KEY=","FREELLMAPI_MODEL=auto","LLM_INPUT_USD_PER_MILLION="+inputPrice,"LLM_OUTPUT_USD_PER_MILLION="+outputPrice,"LLM_CONTEXT_TOKENS=4096","LLM_MAX_OUTPUT_TOKENS=1024"]:["LLM_MODEL_PROTOCOL=hosted-credit-sse","HOSTED_API_BASE_URL=","HOSTED_API_KEY=","HOSTED_MODEL=auto-cheapest","HOSTED_PROVIDER_TAG=","LLM_MARKUP_BPS=23000","LLM_CONTEXT_TOKENS=32768","LLM_MAX_OUTPUT_TOKENS=4096"];
 const railway=[...common,...serving].join("\n"),vercel="LLM_BACKEND_URL="+backendOrigin,commands="cd /app\nnode scripts/"+(route==="freellmapi"?"activate-router.mjs":"activate-funded.mjs")+" --buffer "+(validBuffer?buffer:"1");
 return <div className="page guides"><header className="page-heading"><span className="eyebrow">FREELM / SERVICE SETUP</span><h1>Connect. Stock. Open checkout.</h1><p>Copy configuration blocks into your host. These inputs stay in this browser. Provider credentials belong in server variables.</p></header><div className="setup-grid"><label>Serving route<select aria-label="Serving route" value={route} onChange={e=>setRoute(e.target.value)}><option value="freellmapi">FreeLLMAPI · free-tier router</option><option value="hosted">Existing funded serving adapter</option></select></label><label>Railway HTTPS origin<input aria-label="Railway HTTPS origin" value={backend} onChange={e=>setBackend(e.target.value)} placeholder="Your existing account service HTTPS origin" type="url"/></label><label>USDC recipient wallet<input aria-label="USDC recipient wallet" value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Your public receiving address"/></label><label>Safety buffer (USD)<input aria-label="Safety buffer (USD)" value={buffer} onChange={e=>setBuffer(e.target.value)} inputMode="decimal"/></label>{route==="freellmapi"&&<><label>FreeLLMAPI router base URL<input aria-label="FreeLLMAPI router base URL" value={router} onChange={e=>setRouter(e.target.value)} placeholder="https://your-router-host/v1" type="url"/></label><label>Input service price · USD / 1M tokens<input aria-label="Input service price" value={inputPrice} onChange={e=>setInputPrice(e.target.value)} inputMode="decimal" placeholder="Your published exact rate"/></label><label>Output service price · USD / 1M tokens<input aria-label="Output service price" value={outputPrice} onChange={e=>setOutputPrice(e.target.value)} inputMode="decimal" placeholder="Your published exact rate"/></label></>}</div>{((backend&&!backendOrigin)||(recipient&&!wallet)||(router&&!base)||!validBuffer)&&<p role="alert">Use valid HTTPS URLs, a public Solana address and an exact USD buffer.</p>}
 <p className="setup-note">FreeLLMAPI is self-hosted. Deploy the separate router from /release/router, add usable free-tier provider keys to its dashboard, and copy its unified key into FREELLMAPI_API_KEY in the existing FreeLM account service. The freellmapi.co website is not your inference endpoint. <a href="/docs/model#router-setup">Read router setup →</a></p>
 <Block title="Railway variables" value={railway}/><Block title="Vercel variables" value={vercel}/><p className="setup-note">Keep the account service’s existing /data volume and ledger. Apply changed variables individually so blank fields never replace existing secrets. PAYMENT_RECIPIENT receives canonical Solana USDC; use the public address. Deploy after variable changes.</p><Block title="Activation command" value={commands}/><p className="setup-note">{route==="freellmapi"?"The router command checks ready models, runs a streamed usage probe and opens only funded $1 checkout. Record cleared operator funding before activation; free quotas are not cash reserves.":"The existing funded command verifies paid serving capacity, imports cleared stock once and checks a streamed response."} Daily holder issuance remains zero. API and redemption codes are separate from account credit purchases.</p></div>;
}
