import {useEffect,useRef,useState} from "react";
import links from "../public/brand/links.json";
import {contractAddress,xProfile} from "./social-config";
export function BrandSymbol(){return <img className="official-brand-logo" src="/brand/local-llm-server-cube.jpg" alt="" aria-hidden="true" width="40" height="40"/>;}
export function SocialControls({mint}:{mint?:unknown}){const ca=contractAddress(mint||import.meta.env.VITE_LLM_CA||links.contractAddress),x=xProfile(import.meta.env.VITE_X_URL||links.xUrl),[state,setState]=useState(""),input=useRef<HTMLInputElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
useEffect(()=>{setState("");},[ca]);
async function copy(){if(!ca)return;try{await navigator.clipboard.writeText(ca);setState("Copied");}catch{input.current?.focus();input.current?.select();setState("Select CA to copy");}if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setState(""),2500);}
const icon=<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18.9 2H22l-6.8 7.8L23.2 22h-6.3L12 14.6 5.5 22H2.3l7.3-8.4L1.9 2h6.5l4.5 6.8L18.9 2Zm-1.1 18h1.7L7.4 4H5.6L17.8 20Z" fill="currentColor"/></svg>;
return <div className="social-controls">{x?<a className="social-x" href={x} target="_blank" rel="noopener noreferrer" aria-label="FreeLM on X">{icon}</a>:<button className="social-x" type="button" disabled aria-label="FreeLM on X" title="X profile coming soon">{icon}</button>}<div className="social-ca"><label htmlFor="llm-contract-address">CA</label><input ref={input} id="llm-contract-address" aria-label="Contract address" value={ca} readOnly title={ca||"Contract address coming soon"} onFocus={e=>e.currentTarget.select()}/><button type="button" onClick={()=>void copy()} disabled={!ca} aria-label="Copy contract address" title={ca?"Copy contract address":"Contract address coming soon"}>{state==="Copied"?<span aria-hidden="true">✓</span>:<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M8 8h12v12H8zM16 8V4H4v12h4" stroke="currentColor" strokeWidth="1.6"/></svg>}</button></div><span className="social-feedback" role="status" aria-live="polite">{state}</span></div>;}
