import {useEffect,useRef,useState} from "react";
import {HardwareSetup} from "./hardware";
import {baselines,compareCost} from "./comparison";

const architecture = [
  {name:"Your context",subtitle:"Prepare on your device",state:"WORKING IN BROWSER",icon:"01",body:"Paste your notes, import text and review exact paragraph deduplication. Download the pack or place it in a chat draft. The context tool makes no upload request.",detail:"Local processing · explicit sharing · measured text size"},
  {name:"Your identity",subtitle:"Wallet + scoped API keys",state:"IMPLEMENTED IN BACKEND",icon:"02",body:"Sign a one-time wallet message to authenticate. Developer keys are scoped, stored as hashes and revocable. Account availability is shown in the workspace.",detail:"Signed nonce · session boundary · per-key spending cap"},
  {name:"The credit ledger",subtitle:"Reserve, execute, settle",state:"IMPLEMENTED IN BACKEND",icon:"03",body:"Daily allowances, purchases and verified burns feed one usage balance. The ledger reserves credit before inference, settles verified usage and releases unused credit without double spending.",detail:"Funded allocations · atomic reservations · receipt verification"},
  {name:"FreeLM",subtitle:"Our custom inference endpoint",state:"IN DEVELOPMENT",icon:"04",body:"This is where the custom model will serve responses. We’re selecting the model and serving setup, then measuring quality and cost before opening access. Explore our dedicated four-GPU stack below.",detail:"Selected weights → evaluated serving runtime → metered endpoint"},
  {name:"Your next answer",subtitle:"Workspace + developer tools",state:"INTERFACE READY",icon:"05",body:"The workspace displays streamed responses and usage receipts when a serving endpoint is active. Context Studio already works independently. You choose which context to send; imported notes are not automatically training data.",detail:"One workspace · one usage balance · inspectable accounting"},
];

export function CostComparison({compact=false}:{compact?:boolean}) {
  const [baseline,setBaseline]=useState("sol"),[input,setInput]=useState("1"),[output,setOutput]=useState("0.25"),[inputRate,setInputRate]=useState("0.10"),[outputRate,setOutputRate]=useState("0.50");
  const base=baselines.find(item=>item.id===baseline)!;
  const values=[input,output,inputRate,outputRate].map(Number);
  const valid=[input,output,inputRate,outputRate].every(v=>v.trim()!=="")&&values.every(v=>Number.isFinite(v)&&v>=0&&v<=1_000_000);
  const result=valid?compareCost(values[0],values[1],values[2],values[3],base):null;
  const dollars=(n:number)=>n.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:4});
  return <section className={"cost-comparison "+(compact?"compact":"")} id="cost-lab">
    <div className="section-label"><span>THE COST LAB</span><span>INTERACTIVE / SCENARIO</span></div>
    <div className="comparison-heading"><h2>Better economics.<br/><span>Show the math.</span></h2><p>Our engineering target is 90–95% lower standard API cost against selected premium models. Explore the rates that would make it possible.</p></div>
    <div className="scenario-notice">PLANNING SCENARIO · FreeLM has no published serving price or verified savings benchmark yet. The target rates below are editable assumptions, not a purchasable offer.</div>
    <div className="comparison-layout"><div className="comparison-controls"><label>Compare with<select value={baseline} onChange={e=>setBaseline(e.target.value)}>{baselines.map(item=><option key={item.id} value={item.id}>{item.name} · {item.company}</option>)}</select></label><div className="compare-input-grid"><label>Monthly input · million tokens<input type="number" min="0" max="1000000" step="0.1" value={input} onChange={e=>setInput(e.target.value)}/></label><label>Monthly output · million tokens<input type="number" min="0" max="1000000" step="0.1" value={output} onChange={e=>setOutput(e.target.value)}/></label><label>Target input price · $ / 1M<input type="number" min="0" max="1000000" step="0.01" value={inputRate} onChange={e=>setInputRate(e.target.value)}/></label><label>Target output price · $ / 1M<input type="number" min="0" max="1000000" step="0.01" value={outputRate} onChange={e=>setOutputRate(e.target.value)}/></label></div><a href={base.source} target="_blank" rel="noreferrer" className="source-link">Published baseline: ${base.input} input / ${base.output} output per 1M ↗</a></div><div className="comparison-result" aria-live="polite">{result?<><span className="eyebrow">ILLUSTRATIVE COST DIFFERENCE</span><strong>{result.savings===null?"—":Math.abs(result.savings).toFixed(1)+"%"}</strong><p>{result.savings===null?"Add usage to compare.":result.savings===0?"Same assumed cost.":result.savings>0?"lower at these target rates":"higher at these target rates"}</p><dl><div><dt>{base.name}</dt><dd>{dollars(result.reference)}</dd></div><div><dt>FreeLM · hypothetical</dt><dd>{dollars(result.proposed)}</dd></div></dl></>:<p role="alert">Enter non-negative values in all four fields.</p>}</div></div>
    <p className="comparison-method">API comparison, not ChatGPT or Claude subscriptions. Standard uncached text rates checked October 1, 2026; excludes batch, tools, taxes and long-context premiums. Assumes short requests with the same aggregate token counts. Tokenizers and model quality differ. No equivalent-capability claim; 95% savings does not apply to every model. Infrastructure cost and holder subsidies are separate from retail pricing.</p>
  </section>;
}

export function ProductStory() {
  const [active,setActive]=useState("why-local"),[stage,setStage]=useState(0);
  const root=useRef<HTMLDivElement>(null);
  useEffect(()=>{
    const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)setActive(entry.target.id);},{rootMargin:"-15% 0px -50% 0px",threshold:0});
    root.current?.querySelectorAll("[data-chapter]").forEach(section=>observer.observe(section));
    return()=>observer.disconnect();
  },[]);
  const selected=architecture[stage];
  return <div className="product-story" ref={root}>
    <nav className="chapter-nav" aria-label="Explore FreeLM">{[["why-local","Why local"],["infrastructure","Our architecture"],["our-setup","Our hardware"],["economics","The economics"]].map(([id,label])=><a key={id} href={"#"+id} className={active===id?"selected":""} aria-current={active===id?"location":undefined}>{label}<span>↘</span></a>)}</nav>
    <section className="story-section why-local" id="why-local" data-chapter><div className="section-label"><span>01 / WHY LOCAL</span><span>MORE CONTROL. LESS REPEAT WORK.</span></div><div className="story-heading"><h2>Intelligence should work<br/><span>on your terms.</span></h2><p>The local-first direction is about control over your context, your compute and your spending. It starts with tools you can inspect.</p></div><div className="why-grid"><article><span className="why-icon">↳</span><h3>Context you choose.</h3><p>Prepare notes in your browser. See what changes. Decide what enters a conversation before you send it.</p><a href="/context">Try the context studio ↗</a></article><article><span className="why-icon">◇</span><h3>Compute with a purpose.</h3><p>Our custom-model roadmap focuses on useful workloads, selected weights and measured quality—then deployment on hardware we control.</p><a href="#our-setup">Explore our hardware ↓</a></article><article><span className="why-icon">◎</span><h3>A daily place to build.</h3><p>Eligible $LLM holders share a funded daily allowance. The same credits can power the workspace and API when inference is available.</p><a href="/credits">See holder access ↗</a></article></div></section>
    <section className="story-section infrastructure" id="infrastructure" data-chapter><div className="section-label"><span>02 / OUR ARCHITECTURE</span><span>EXPLORE EACH LAYER</span></div><div className="story-heading"><h2>From your knowledge<br/><span>to your next answer.</span></h2><p>A clear path through the product. Select a layer to see its role and current implementation status.</p></div><div className="architecture-steps" role="group" aria-label="Infrastructure layers">{architecture.map((item,index)=><button key={item.name} className={stage===index?"selected":""} aria-pressed={stage===index} onClick={()=>setStage(index)}><span>{item.icon}</span><strong>{item.name}</strong><small>{item.subtitle}</small></button>)}</div><div className="architecture-detail" aria-live="polite"><div><span className="eyebrow">LAYER {selected.icon}</span><h3>{selected.name}</h3><span className="architecture-state">{selected.state}</span></div><div><p>{selected.body}</p><small>{selected.detail}</small></div></div><p className="story-footnote">Wallet access, metered compute and a shared balance across the workspace and API. Model details show current serving availability.</p></section>
    <HardwareSetup/>
    <section className="story-section economics" id="economics" data-chapter><div className="section-label"><span>04 / THE ECONOMICS</span><span>UTILITY YOU CAN PUT TO WORK</span></div><div className="story-heading"><h2>A token with<br/><span>work to do.</span></h2><p>Daily access for holders. Extra capacity for builders. A funded reserve behind the usage.</p></div><div className="economy-flow"><div><small>01 / FUND</small><h3>Actual revenue</h3><p>Credit purchases and received creator fees provide operating funds. Token price and projected volume are not revenue.</p></div><span>→</span><div><small>02 / RESERVE</small><h3>Cover the compute</h3><p>Honor outstanding credits and operating costs first. Only cleared, uncommitted funding supports new holder allocations.</p></div><span>→</span><div><small>03 / USE</small><h3>Put credits to work</h3><p>Holders claim their funded share. Buyers add prepaid usage. Token burns redeem additional, reserve-backed capacity.</p></div></div><div className="economy-rule"><span>HOLD → CLAIM → USE</span><p>Daily credits expire after 24 hours. Purchases and burn credits do not expire daily. Burns reduce token supply; they do not pay the compute bill. Credits provide AI usage, not a share of project profits.</p><a href="/transparency">Inspect the funding ledger ↗</a></div></section>
    <CostComparison compact/>
    <div className="docs-invite"><div><span className="eyebrow">THE FREELM FIELD GUIDE</span><h2>Understand it.<br/>Then build with it.</h2></div><div><a href="/docs#utility">Token utility & daily credits ↗</a><a href="/docs#revenue">Revenue & reserve accounting ↗</a><a href="/docs#setup">Infrastructure & model roadmap ↗</a><a href="/pricing">Pricing & comparison methodology ↗</a></div></div>
  </div>;
}
