import {test,expect} from "@playwright/test";
const routes=[["/docs","Local LLM, explained."],["/docs/llm","$LLM token"],["/docs/credits","Compute credits"],["/docs/model","LocalLM model"],["/docs/network","Compute network"],["/docs/buyback-burn","Buyback + Burn"],["/docs/api","Developer API"],["/docs/security","Security + privacy"],["/docs/roadmap","Roadmap"],["/docs/benchmarks","Benchmarks"]] as const;
for(const width of [1440,390,320])for(const [url,title]of routes)test("docs "+url+" at "+width+"px",async({page})=>{
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.setViewportSize({width,height:960});await page.goto(url);await expect(page.getByRole("heading",{level:1,name:title,exact:true})).toBeVisible();await expect(page).toHaveTitle(new RegExp("Local Language Model Docs"));await expect(page.locator(".docs-brand .official-brand-logo")).toHaveAttribute("src","/brand/local-llm-server-cube.jpg");expect(await page.locator(".docs-brand img").evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))console.log("DOCS_OVERFLOW",url,width,await page.evaluate(()=>Array.from(document.querySelectorAll(".docs-shell *")).filter(n=>n.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(n=>({tag:n.tagName,class:n.className,right:n.getBoundingClientRect().right,scroll:n.scrollWidth,width:n.clientWidth}))));await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(width<761){const toggle=page.getByRole("button",{name:"Toggle documentation navigation"});await expect(toggle).toHaveAttribute("aria-expanded","false");await expect(page.getByRole("navigation",{name:"Documentation navigation",exact:true})).toBeHidden();await toggle.click();await expect(toggle).toHaveAttribute("aria-expanded","true");}
 const nav=page.getByRole("navigation",{name:"Documentation navigation",exact:true});await expect(nav.locator('a[aria-current="page"]')).toHaveAttribute("href",url);await expect(nav.getByRole("link")).toHaveCount(10);
 if(width<761)await page.getByRole("button",{name:"Toggle documentation navigation"}).click();await page.locator(".docs-section").last().getByRole("heading",{level:2}).getByRole("link").click();await expect(page).toHaveURL(new RegExp("#"));await page.reload();await expect(page.locator(".docs-section").last().getByRole("heading",{level:2})).toBeInViewport();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);if(url==="/docs"||url==="/docs/buyback-burn")await page.screenshot({path:"test-results/docs-"+url.split("/").pop()+"-"+width+".png",fullPage:true});
});
test("primary DOCS navigation and mobile article navigation work",async({page})=>{await page.goto("/");await page.locator(".compute-nav-links").getByRole("link",{name:"DOCS",exact:true}).click();await expect(page).toHaveURL(/\/docs$/);await page.setViewportSize({width:390,height:900});await page.getByRole("button",{name:"Toggle documentation navigation"}).click();await page.getByRole("navigation",{name:"Documentation navigation",exact:true}).getByRole("link",{name:"Compute credits",exact:true}).click();await expect(page).toHaveURL(/\/docs\/credits$/);await expect(page.getByRole("heading",{name:"Compute credits",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Toggle documentation navigation"})).toHaveAttribute("aria-expanded","false");});
test("API examples copy with service variables and no private keys",async({page})=>{await page.addInitScript(()=>{Object.defineProperty(navigator,"clipboard",{value:{writeText:async(value:string)=>{(window as any).copiedDocCode=value;}}});});await page.goto("/docs/api");await page.getByRole("button",{name:"Copy curl example",exact:true}).click();expect(await page.evaluate(()=>(window as any).copiedDocCode)).toContain("OUR_API_BASE_URL");expect(await page.evaluate(()=>(window as any).copiedDocCode)).toContain("OUR_USER_API_KEY");await page.getByRole("button",{name:"Copy JavaScript example",exact:true}).click();const js=await page.evaluate(()=>(window as any).copiedDocCode);expect(js).toContain("/chat/completions");expect(()=>new Function("return (async()=>{"+js+"})")).not.toThrow();});
test("buyback documentation has honest empty state and no invented supply metric",async({page})=>{await page.goto("/docs/buyback-burn");await expect(page.locator(".docs-burn-total>strong")).toHaveText("—");await expect(page.locator(".docs-empty")).toContainText("No verified buyback or burn");await expect(page.locator(".docs-article-heading .docs-status")).toHaveText("PLANNED");await expect(page.locator(".docs-transaction")).toHaveCount(0);});
test("future verified receipt schema displays exact token amounts and real transaction links",async({page})=>{const signature="1".repeat(88);await page.route("**/api/buybacks",route=>route.fulfill({json:{status:"planned",network:"solana-mainnet",mint:"controlled-mint",decimals:6,cumulativeBurnAtomic:"900719925474099312345",observedAt:null,transactions:[{verified:true,network:"solana-mainnet",mint:"controlled-mint",signature,atomicAmount:"1234567",decimals:6},{verified:false,network:"solana-mainnet",mint:"controlled-mint",signature:"2".repeat(88),atomicAmount:"999999999999",decimals:6}]}}));await page.goto("/docs/buyback-burn");await expect(page.locator(".docs-burn-total>strong")).toHaveText("900,719,925,474,099.312345");await expect(page.locator(".docs-transaction")).toHaveCount(1);await expect(page.locator(".docs-transaction")).toHaveAttribute("href","https://solscan.io/tx/"+signature);await expect(page.locator(".docs-burn-records")).toContainText("1.234567");});
test("unknown documentation URL has a shareable not-found state",async({page})=>{await page.goto("/docs/missing");await expect(page.getByRole("heading",{name:"Documentation page not found."})).toBeVisible();await page.getByRole("link",{name:"Read the overview"}).click();await expect(page).toHaveURL(/\/docs$/);});
