import {test,expect} from "@playwright/test";
for(const width of [1440,390,320])test("FreeLM brand and isolated router setup at "+width+"px",async({page})=>{
 await page.setViewportSize({width,height:960});await page.goto("/");
 await expect(page.locator(".compute-brand")).toContainText("FREELM");await expect(page).toHaveTitle(/FreeLM/);await expect(page.getByRole("link",{name:"FreeLM on X"})).toHaveAttribute("href","https://x.com/LocalLM_");await expect(page.locator(".compute-logo img")).toHaveAttribute("src","/brand/local-llm-server-cube.jpg");await expect(page.locator(".compute-status-line")).toContainText("MODEL ROUTING");await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.goto("/setup");await expect(page.getByRole("combobox",{name:"Serving route"})).toHaveValue("freellmapi");
 await page.getByRole("textbox",{name:"FreeLLMAPI router base URL"}).fill("https://router.example.test/v1");await page.getByRole("textbox",{name:"Input service price",exact:true}).fill("0.4");await page.getByRole("textbox",{name:"Output service price",exact:true}).fill("1.6");let vars=await page.getByRole("textbox",{name:"Railway variables",exact:true}).inputValue();expect(vars).toContain("FREELLMAPI_BASE_URL=https://router.example.test/v1");expect(vars).toContain("FREELLMAPI_API_KEY=\n");expect(vars).toContain("LLM_INPUT_USD_PER_MILLION=0.4");expect(vars).toContain("LLM_OUTPUT_USD_PER_MILLION=1.6");await expect(page.getByRole("textbox",{name:"Activation command"})).toHaveValue(/activate-router\.mjs/);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole("combobox",{name:"Serving route"}).selectOption("hosted");await expect(page.getByRole("textbox",{name:"Railway variables",exact:true})).toHaveValue(/LLM_MODEL_PROTOCOL=hosted-credit-sse/);
 await page.goto("/docs/model");await expect(page.getByRole("heading",{level:1,name:"FreeLM model",exact:true})).toBeVisible();await expect(page.locator("#router-setup")).toContainText("BUILDING");await expect(page.locator("#router-setup")).toContainText("free-tier");await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
