import {test,expect} from "@playwright/test";
const site=process.env.OUR_PUBLIC_PREVIEW_URL??"https://local-language-model.vercel.app";
for(const width of [1440,390])test("public Vercel compute preview at "+width+"px",async({page,request})=>{
 test.setTimeout(180000);await page.setViewportSize({width,height:960});const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 await page.goto(site,{waitUntil:"domcontentloaded"});await expect(page.getByRole("heading",{name:"HOLD $LLM. USE AI."})).toBeVisible({timeout:120000});
 const status=await request.get(site+"/api/status");expect(status.status()).toBe(200);const s=await status.json();expect(s.name).toBe("Local Language Model");expect(s.model.id).toBe("local-language-model");expect(JSON.stringify(s)).not.toContain("gpt-4.1");
 const network=await request.get(site+"/api/network");expect(network.status()).toBe(200);const n=await network.json();expect(n.metrics).toBeDefined();expect(n.architecture).toHaveLength(6);
 await expect(page.locator(".compute-page")).not.toContainText(/the repository|operator.confirmation|operator-confirmed|operator-attested/i);
 await expect(page.locator(".compute-built")).toContainText("DEDICATED GPU INFRASTRUCTURE");
 await expect(page.locator(".compute-telemetry dd")).toHaveCount(6);if(n.telemetryStatus!=="reporting")await expect(page.locator(".compute-telemetry dd")).toHaveText(["—","—","—","—","—","—"]);
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator(".compute-hero").getByRole("button",{name:"CONNECT WALLET",exact:true}).click();await expect(page.getByRole("heading",{name:"Connect your wallet"})).toBeVisible();await page.getByRole("button",{name:"Close",exact:true}).click();
 await page.screenshot({path:"test-results/public-compute-"+width+".png",fullPage:true});expect(errors).toEqual([]);
});

test("deployed brand assets, canonical copy control and X button are available",async({page,request})=>{
 test.setTimeout(180000);
 await expect.poll(async()=>{const r=await request.get(site+"/brand/llm-symbol.svg");return (await r.text()).includes('viewBox="0 0 32 32"');},{timeout:150000,intervals:[3000,5000,10000]}).toBe(true);
 const logo=await request.get(site+"/brand/llm-symbol.svg");expect(logo.headers()["content-type"]).toContain("image/svg+xml");expect(await logo.text()).not.toContain("<text");
 for(const asset of ["llm-logo.png","llm-x-banner.png"]){const image=await request.get(site+"/brand/"+asset);expect(image.status()).toBe(200);expect(image.headers()["content-type"]).toContain("image/png");}
 const banner=await request.get(site+"/brand/llm-banner.svg");expect(await banner.text()).toContain('width="1500" height="500"');
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});await page.goto(site);await expect(page.getByRole("textbox",{name:"Contract address"})).toHaveValue("AysAW2C9yN5SDmPkXdEwByTfmYioYbgExkRKYgU1pump");await expect(page.getByRole("button",{name:"Copy contract address"})).toBeEnabled();await expect(page.getByRole("link",{name:"Local Language Model on X"})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
});

test("deployed docs, manifesto and launch packages are current and shareable",async({page,request})=>{test.setTimeout(240000);await expect.poll(async()=>{await page.goto(site+"/docs/credits");return await page.getByRole("heading",{name:"Compute credits",exact:true}).count();},{timeout:180000,intervals:[3000,5000,10000]}).toBe(1);for(const [url,title]of [["/docs","Local LLM, explained."],["/docs/llm","$LLM token"],["/docs/model","LocalLM model"],["/docs/network","Compute network"],["/docs/buyback-burn","Buyback + Burn"],["/docs/api","Developer API"],["/docs/security","Security + privacy"],["/docs/roadmap","Roadmap"],["/docs/benchmarks","Benchmarks"]]){await page.goto(site+url);await expect(page.getByRole("heading",{level:1,name:title,exact:true})).toBeVisible();}await page.setViewportSize({width:390,height:900});await page.goto(site+"/docs");await page.getByRole("button",{name:"Toggle documentation navigation"}).click();await expect(page.getByRole("navigation",{name:"Documentation navigation",exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.goto(site);await expect(page.locator("#manifesto")).toContainText("KEEP IDEAS FREE");await page.goto(site+"/credits");await expect(page.getByRole("button",{name:"$1",exact:true})).toHaveAttribute("aria-pressed","true");for(const dollars of [5,10,20])await expect(page.getByRole("button",{name:"$"+dollars+" coming soon",exact:true})).toBeDisabled();const feed=await request.get(site+"/api/buybacks");expect(feed.status()).toBe(200);expect((await feed.json()).cumulativeBurnAtomic).toBeNull();});

test("record deployed account, pricing and payment availability without exposing secrets",async({request})=>{test.setTimeout(180000);await expect.poll(async()=>{const r=await request.get(site+"/api/status");return r.headers()["x-llm-gateway-version"];},{timeout:150000,intervals:[3000,5000,10000]}).toBe("url-diagnostics-1");const response=await request.get(site+"/api/status");const s=await response.json();const observed={httpStatus:response.status(),backendConfigurationIssue:s.configurationIssue??null,backendUrlInvalid:s.error==="The persistent backend URL must be a different, valid HTTPS origin.",backendConnected:s.backendConfigured===true,modelAvailable:s.model?.available===true,assistant:s.model?.name,inputPerMillion:s.model?.inputPerMillion??null,outputPerMillion:s.model?.outputPerMillion??null,purchaseConfigured:s.purchaseConfigured===true,burnConfigured:s.burnConfigured===true,dailyBudget:s.dailyBudget??0,newIssuancePaused:s.paused===true,purchaseStock:s.purchaseStock??null};console.log("LIVE_AVAILABILITY "+JSON.stringify(observed));expect(response.ok()).toBe(true);expect(JSON.stringify(s)).not.toMatch(/HOSTED_API_KEY|ADMIN_KEY|sk-or-v1-/);});
