import {createServer} from "node:http";
import {readFile} from "node:fs/promises";
import {resolve,extname} from "node:path";
import {database} from "./database";
import {Service} from "./service";
const production=process.env.NODE_ENV==="production";if(production&&(!process.env.PUBLIC_URL||new URL(process.env.PUBLIC_URL).protocol!=="https:"))throw new Error("Production requires PUBLIC_URL with the exact HTTPS origin.");
const service=new Service(database(process.env.DB_PATH??"./data/llm.sqlite"));service.f.recover(true);
const root=resolve("dist");const mime:Record<string,string>={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".svg":"image/svg+xml",".png":"image/png",".ico":"image/x-icon",".json":"application/json"};
const server=createServer(async(req,res)=>{try{const url=new URL(req.url??"/",process.env.PUBLIC_URL??"http://localhost:3000");if(url.pathname.startsWith("/api/")){let size=0;const chunks:Buffer[]=[];for await(const chunk of req){size+=chunk.length;if(size>48000){res.writeHead(413);res.end("Request too large");return;}chunks.push(chunk);}const headers=new Headers();for(const [key,value] of Object.entries(req.headers)){if(value)headers.set(key,Array.isArray(value)?value.join(","):value);}const request=new Request(url,{method:req.method,headers,...(req.method!=="GET"&&req.method!=="HEAD"?{body:Buffer.concat(chunks) as any}:{})});const response=await service.handle(request);res.writeHead(response.status,Object.fromEntries(response.headers));if(response.body){const reader=response.body.getReader();while(true){const part=await reader.read();if(part.done)break;if(!res.destroyed&&!res.writableEnded)res.write(part.value);} }res.end();return;}
 if(req.method!=="GET"&&req.method!=="HEAD"){res.writeHead(405);res.end();return;}const path=resolve(root,"."+decodeURIComponent(url.pathname));if(path!==root&&!path.startsWith(root+"/")){res.writeHead(403);res.end();return;}let file=path;let data:Buffer;try{data=await readFile(file);}catch{file=resolve(root,"index.html");data=await readFile(file);}res.writeHead(200,{"Content-Type":mime[extname(file)]??"application/octet-stream","Content-Security-Policy":"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'","X-Content-Type-Options":"nosniff","Referrer-Policy":"strict-origin-when-cross-origin","Permissions-Policy":"camera=(), microphone=(), geolocation=()",...(production?{"Strict-Transport-Security":"max-age=63072000; includeSubDomains"}:{})});res.end(req.method==="HEAD"?undefined:data);}catch{if(!res.headersSent)res.writeHead(500,{"Content-Type":"text/plain"});res.end("Service unavailable");}});
server.requestTimeout=100000;server.headersTimeout=15000;server.listen(Number(process.env.PORT??3000),"0.0.0.0",()=>console.log("Local Language Model server ready."));
let working=false;const timer=setInterval(()=>{if(working)return;working=true;void service.maintenance().finally(()=>working=false);},15000);timer.unref();
for(const signal of ["SIGINT","SIGTERM"] as const)process.on(signal,()=>{clearInterval(timer);server.close(()=>{service.db.close();process.exit(0);});setTimeout(()=>process.exit(0),100000).unref();});
