import test from "node:test";
import assert from "node:assert/strict";
import {database,row,rows} from "../server/database";
import {Finance,type Quote} from "../server/finance";
import {DAY,units,money,cost} from "../server/money";
const fixture=()=>{let now=1_800_000_000_000;const db=database(":memory:"),f=new Finance(db,()=>now);f.fund(units("100"),"cleared-receipt","https://example.com/receipt");f.configure(units("10"),units("1"),false);return {db,f,time:()=>now,advance:(n:number)=>{now+=n;}};};
function grant(f:Finance,wallet:string,kind:"purchase"|"burn"="purchase",amount=units("1"),signature="receipt-"+Math.random()){const q=f.quote(wallet,kind,"1000000",amount);f.db.prepare("UPDATE quotes SET state='issued' WHERE id=?").run(q.id);f.receipt(q.id,wallet,signature);return q;}
function eligible(f:Finance,wallet:string,balance=100n){f.observe(wallet,balance,f.now()-DAY);f.db.prepare("UPDATE holds SET evidence_until=? WHERE wallet=?").run(f.now(),wallet);}
function epoch(f:Finance){eligible(f,"alice");return f.openEpoch("2027-01-15",units("1"),100n,f.now()+1000);}
 test("exact decimal accounting and published usage",()=>{assert.equal(units("1.000000001"),1_000_000_001);assert.equal(money(1_000_000_001),"$1.000000001");assert.equal(cost(1000,1000),units("0.002"));assert.throws(()=>units("1.0000000001"));assert.throws(()=>units("1e3"));});
 test("ineligible wallets cannot claim; concurrent eligible claims issue once",async()=>{const {f}=fixture();epoch(f);assert.throws(()=>f.claim("bob","2027-01-15"));const results=await Promise.allSettled([Promise.resolve().then(()=>f.claim("alice","2027-01-15")),Promise.resolve().then(()=>f.claim("alice","2027-01-15"))]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(f.available("alice"),units("1"));});
 test("historical proof must cover a full 24 hours; receiving restarts qualification",()=>{const {f}=fixture();f.observe("alice",100n,f.now()-DAY);assert.throws(()=>f.openEpoch("old",units("1"),100n,f.now()+1000));f.db.prepare("UPDATE holds SET evidence_until=? WHERE wallet='alice'").run(f.now());f.openEpoch("old",units("1"),100n,f.now()+1000);f.observe("alice",0n,f.now());f.observe("bob",100n,f.now());assert.throws(()=>f.claim("bob","old"));assert.throws(()=>f.openEpoch("new",units("1"),100n,f.now()+1000));});
 test("splitting equal eligible balance never increases rounded reward",()=>{const {f}=fixture();eligible(f,"a",100n);eligible(f,"b",50n);eligible(f,"c",50n);const a=f.openEpoch("split",101,1n,f.now()+1000);assert.equal(a.find(x=>x.wallet==="a")!.amount,50);assert.equal(a.filter(x=>x.wallet!=="a").reduce((n,x)=>n+x.amount,0),50);});
 test("excluded addresses cannot receive allocation",()=>{const {f}=fixture();eligible(f,"treasury");f.db.prepare("UPDATE holds SET excluded=1 WHERE wallet='treasury'").run();assert.throws(()=>f.openEpoch("excluded",units("1"),100n,f.now()+1000));});
 test("daily lots expire exactly; purchased and burn lots remain",()=>{const {f,advance}=fixture();epoch(f);const claimed=f.claim("alice","2027-01-15");assert.equal(claimed.expires,f.now()+DAY);grant(f,"alice","purchase",units("1"));grant(f,"alice","burn",units("1"));advance(DAY);f.recover();assert.equal(f.available("alice"),units("2"));assert.equal(rows(f.db,"SELECT * FROM ledger WHERE kind='expiration'").length,1);});
 test("earliest-expiring credits are reserved and settled first; ledger balances agree",()=>{const {f}=fixture();epoch(f);f.claim("alice","2027-01-15");grant(f,"alice");const id=f.reserve("alice",units("1.5"),null,null);f.dispatched(id);f.settle(id,units("1.2"),1000,1000,"provider");const lots=rows<{kind:string,available:number}>(f.db,"SELECT * FROM lots WHERE wallet='alice'");assert.equal(lots.find(x=>x.kind==="daily")!.available,0);assert.equal(lots.find(x=>x.kind==="purchased")!.available,units("0.8"));assert.equal(row<{n:number}>(f.db,"SELECT SUM(available_delta) n FROM ledger WHERE wallet='alice'")!.n,f.available("alice"));});
 test("unused expired daily reservation is never returned as usable credit",()=>{const {f,advance}=fixture();epoch(f);f.claim("alice","2027-01-15");const id=f.reserve("alice",units("1"),null,null);f.dispatched(id);advance(DAY);f.recover();f.settle(id,units("0.2"),1,1,"verified");assert.equal(f.available("alice"),0);assert.equal(f.capacity().obligations,0);});
 test("concurrent reservations cannot overspend an account",async()=>{const {f}=fixture();grant(f,"alice");const requests=await Promise.allSettled([Promise.resolve().then(()=>f.reserve("alice",units("0.8"),null,null)),Promise.resolve().then(()=>f.reserve("alice",units("0.8"),null,null))]);assert.equal(requests.filter(x=>x.status==="fulfilled").length,1);assert.equal(f.available("alice"),units("0.2"));});
 test("receipt replay never credits purchase or burn twice",()=>{const {f}=fixture();const p=grant(f,"alice","purchase",units("1"),"same-receipt");assert.equal(f.receipt(p.id,"alice","same-receipt").duplicate,true);const b=f.quote("alice","burn","1",units("1"));f.db.prepare("UPDATE quotes SET state='issued' WHERE id=?").run(b.id);assert.throws(()=>f.receipt(b.id,"alice","same-receipt"));assert.equal(f.available("alice"),units("1"));});
 test("insufficient reserve blocks new allocations and quotes",()=>{const db=database(":memory:"),f=new Finance(db);f.configure(units("10"),0,false);eligible(f,"alice");assert.throws(()=>f.quote("alice","burn","1",units("1")));assert.throws(()=>f.openEpoch("no-funds",units("1"),1n,f.now()+1000));});
 test("overlapping issued credits remain fully reserved; pause honors existing quotes",()=>{const {f}=fixture();epoch(f);f.claim("alice","2027-01-15");const q=f.quote("bob","burn","1",units("1"));f.db.prepare("UPDATE quotes SET state='issued' WHERE id=?").run(q.id);const before=f.capacity().free;f.configure(units("10"),units("1"),true);assert.throws(()=>f.quote("bob","burn","1",1));f.receipt(q.id,"bob","late-valid-receipt");assert.equal(f.available("bob"),units("1"));assert.equal(f.capacity().free,before);});
 test("key cap includes outstanding reservations and revoked keys cannot reserve",()=>{const {f}=fixture();grant(f,"alice");f.db.prepare("INSERT INTO api_keys(id,wallet,name,hash,cap,created) VALUES('key','alice','test','hash',?,?)").run(units("0.5"),f.now());const id=f.reserve("alice",units("0.4"),"key",null);assert.throws(()=>f.reserve("alice",units("0.2"),"key",null));f.db.prepare("UPDATE api_keys SET revoked=1 WHERE id='key'").run();f.dispatched(id);f.settle(id,units("0.2"),1,1,"provider");assert.throws(()=>f.reserve("alice",1,"key",null));assert.equal(row<{spent:number}>(f.db,"SELECT * FROM api_keys WHERE id='key'")!.spent,units("0.2"));});
 test("restart recovery releases only undispatched reservations and holds uncertain execution",()=>{const {f}=fixture();grant(f,"alice");const a=f.reserve("alice",units("0.2"),null,null),b=f.reserve("alice",units("0.3"),null,null);f.dispatched(b);f.recover(true);assert.equal(f.request(a)!.state,"released");assert.equal(f.request(b)!.state,"uncertain");assert.equal(f.available("alice"),units("0.7"));assert.throws(()=>f.dispatched(a));f.settle(b,units("0.1"),1,1,"verified");f.settle(b,units("0.1"),1,1,"verified");assert.equal(f.available("alice"),units("0.9"));});
 test("unclaimed allocations expire without rollover and ledger is immutable",()=>{const {f,advance}=fixture();epoch(f);const before=f.capacity().free;advance(1000);f.recover();assert.equal(f.capacity().free,before+units("1"));assert.throws(()=>f.claim("alice","2027-01-15"));grant(f,"alice");assert.throws(()=>f.db.exec("DELETE FROM ledger"));assert.throws(()=>f.db.exec("UPDATE ledger SET available_delta=0"));});
